apiVersion: v2
name: envoy-gateway
description: Envoy Gateway
version: 0.1.0
dependencies:
  - name: gateway-helm
    version: 1.7.2
    repository: oci://docker.io/envoyproxy
  - name: homelab-chart
    version: 0.1.30
    repository: oci://ghcr.io/kdwils/charts
    alias: homelab
