argocd:
  global:
    domain: argocd.kyledev.co

  configs:
    cm:
      url: https://argocd.kyledev.co
      admin.enabled: "true"
      accounts.readonly-user: login, apiKey
      statusbadge.enabled: "true"
      statusbadge.url: https://argocd.kyledev.co/
      application.namespaces: "*"
      oidc.config: |
        name: PocketID
        issuer: https://pocketid.kyledev.co
        clientID: 7e697ce9-a9ae-4fae-9782-bb2f575d65a8
        clientSecret: $oidc.pocketid.clientSecret
        requestedScopes: ["openid", "profile", "email", "groups"]
        requestedIDTokenClaims:
          groups:
            essential: true
      resource.customizations: |
        apiextensions.k8s.io/CustomResourceDefinition:
          ignoreDifferences: |
            jsonPointers:
            - /status
        admissionregistration.k8s.io/ValidatingWebhookConfiguration:
          ignoreDifferences: |
            jsonPointers:
            - /webhooks/0/clientConfig/caBundle
            - /webhooks/1/clientConfig/caBundle

      resource.customizations.ignoreDifferences.all: |
        managedFieldsManagers:
          - kube-controller-manager
        jsonPointers:
          - /spec/template/spec/containers/0/resources/requests
          - /spec/template/spec/containers/0/resources/limits

    rbac:
      policy.csv: |
        p, role:admin, *, *, *, allow
        g, admins, role:admin
        g, friends, role:readonly
      policy.default: role:readonly

    params:
      server.insecure: "true"

    secret:
      createSecret: false

  dex:
    enabled: false

  server:
    ingress:
      enabled: false
    service:
      type: ClusterIP

    httproute:
      enabled: false

homelab:
  httproutes:
    - name: argocd-int
      hostnames:
        - argocd.int.kyledev.co
      parentRefs:
        - name: homelab
          namespace: envoy-gateway-system
      rules:
        - backendRefs:
            - group: ""
              kind: Service
              name: argocd-server
              port: 80
    - name: argocd-public
      hostnames:
        - argocd.kyledev.co
        - argocd.ts.kyledev.co
      parentRefs:
        - name: homelab
          namespace: envoy-gateway-system
      rules:
        - backendRefs:
            - group: ""
              kind: Service
              name: argocd-server
              port: 80

  sealedsecrets:
    - name: argocd-secret
      data:
        admin.password: AgAsYrgsW2lP7HtWTh2VAqlpzOgR31hzPzXKvIbrlWZN6f5UKUYM51J5CJsuFJUnaWROfoHfNXBPnrzoZPAORxqFLZKG/6xxeDrtmKRvPGxOCh0iko8ECul76c+5RIjNvE0n+jPnx945QwCjDcu3wSxzhmUz0tBoPeGvhmAT2+80ZkQkJFW2YPH5XY5GoCmnaSIShCqrFwDvnXZfmEwt+HZ8WBPHL7H5NnShPoEjoMtm+QSjMDM2FGRNnhHv5G8H9eHtgNHTTan7YeNriwuLj84RP7B5NNH51IQjTH4y+N1X4YQMIXWJLVI74WSLFOtuHz14OtA4n9HrOYF1uHB4q7YetkHOvCpkBl8lp3gpHWXtxLvfiGCWRy0dXGMRgxFLoulz492KekwXoCOWgJhIgiaXZIvdcOVkZYvBy1yZEKSPMR9rw6kgcl5sxJRkwliq1Qobh0YBQbOtGLClOMCC+ATyN0E5L5sYVxSKD75ZCHDdioRZ3FjAxACRdPBq2DwdB6DfZ5xp2br/dIBrhnTPvKKnhmpUuDFxul39ZTEGK6CergNF8qzLSZou8uTqoKW59XlJWYkmCIZ7UQ5ZPZZttdCTQ9UVyuDGj3Lu0GxGpZ5utwE4FH0R3NuRQJdu/si4h9xHJF4LuCYoMs5MWAEApQX+7alWSk73by4tmkGa0IFN1wrcC70YyRtOdW9tSRRmaITe8H4xWi92FwLeowDQ7gk9mVATM9kqJwEYvTItfANTD/umS3vAmPXTNSP3SAD4sB/G3HLiBQoH8jInRYE=
        admin.passwordMtime: AgAQ3NS5mvr6iuvbHZ/Eklc4iWfvo1F5Wvt7oA4RQfpiOptHW2Je9LeSU1tA7E3PT4QAyGrmsBdlRlJd/XBPBOBQfSnrNzfsL8h9my8zfwq2Z+/4HVbMt+pNcaCFjFLQ7LXQNOkZU3BjFBzLjnlkGpNFmXRQPLF/pfnaiirToIS5TVrWe4zTgVP+sl377IRb0TwU3bSm1gdYcBXiGvDOt10Lpr42GODLbakdP8sxykJwlknbdQU0Qk0W4bmOXa82AD+DmKqW41aUND9MnbN6Iuy+fBZ5yx4ynqc+ndmrw1FO4lAkGszi/WojvKFegoBFzwBM17/Y/8lczHleyY2iG7bSUAqrTqpX/w5nMGkZECv19LJnBaLFvoiO3cpC9xIZL++1T4TsioZTt4ApqodRAxg+Nt7/A+WBuy1emGOiMq/YIT2hnEr9ZJ+vLUYnmFezNnC4U3bSV3LxWoUFa38JaMczYz+Y1URrZ2ygqzp35XdjZCsASm2JVemuikiPqTBMOa0RwySjXcqPQh/SkbaSu+1Ma05Hsu3qfUdurY/GgN/iiqo3l2UBeukhQBaFjdTuZBjRaLlYRuiqSeeNt+XAbwirPPfpTWHFq446+3BcoY46i97dq1rUZ0MkfLckJVJOSReAtpAv+m/m1Yt9Ul30pnOpu+td4WuxpO7hWy3N+l8bPxrdvL/FmCG/iqvD+pa5b7D3RxQ37Ac3dQ7WHLwaL+cwjYAzqQ==
        oidc.pocketid.clientSecret: AgBykibfxo0Cm4pui66oJXdGIShuJ2WbvzUk/j9EJk6GeruGWYOkn1RN1QlN9qJaqmDCzFZ4Dg2MgkecxhzvEcPHw2G5MuQL/jIXg/ui1vy3+ciZV8RCzm4Lqo0p6Trbyz8ar9EFOy4/qxCEiCI33zgYrXLoMODZMok6nXwdK4wWkiAG2StwmIsmwva9hbieZ+kMj+FtdH92o3CJme/RTbbNU8a0VUX1Cw7ck8nIw9na5x7RqIMUfo+9maL2JF79R9TXU0FDeD53qK84xC6JBUqLxsFn0tc20CBJSXHomv11iqS+9bgnbSgjVDAUZ8lBChoDNfA40TJB3aDZj3QplkLL+S2IVwL0YlTHLQuSgTLeDMbG4gUfXvlcvlzpBXD9IU6to8IAHjuB2/w8K6kIlYZkQaGV3wJPAOICWagColXhAPr+5B5YWqANbtbsnZllNrHza1g0Brbt3LRLUk5If8l6NKkw02+NCR1W3xucTEVtZqh/FhlDxuic9TNbgxuU4tfis8dl4VAyDGg30VUR/mNfSzM687wKbqECbEuLWv+DStbsg0Cy2yxCVVAbIHiS7iYhoReAUGvpjgkpShEzVRjYRl8EyUHZnEO7WuF4dZLVR7pq+4go+nzwf15sK3okFz++TrWpwWnqbQBtkbnheyDEANA1MbA0E6+BqJcIa/5AmldAlVSKIhXHNuLwghuEfABTzdQFjMv/179JRG6s1k+pR9EyG/ejdRMdbYIEdn+TWA==
        server.secretkey: AgBlteLLRUBhuoHQIl/gnSBUsxmU6E0FfdMiUv0WV7RBRvs5jH/8LGiOygWwRWUD79UmCnlW1BU7YtUwPScWn5sE5Gf0dsXn9o6AS32vM/3Zirm6LGySgsGpJR6NqIAhtyOWL2kE+8H6Xn9DiyOCGHGxM5M0CAZRT0ELiwwEY2yy0J5/YScwWmWSgAxVYFK6oxeQpjxX8OVbnjuojGhW1UimezKO2tDbywW8II1A+fSEiiCvhIDmzK8jwSpPaRggxLTrQR4/dDOUHNGbtEP32x9Zh9DTWje/bErHdE4VmfFuTaJBJghfIBqHIqbrhLMoFd+fmk5SkjSTpmBYklZvWpjAWa4FukUWErTh0lt/9gUmFBtaydNksvkSNALMgOW/fphQZaY4Cl854vYqO3VKsfcLgeJf8zuiZ56yLtgLORI6FSbOf2lXaHvPN4UYFSJZOT374LbJxVRaw1EpnRBL2BgwohpwwnYbsVPu7tBWk3yeK844stkeGjT8D5M2Z/1dzJad+wY/8eD2qFrL6ozwGxbhK3Smp9+TUfPIiWTKg88WtydET4hHGH5HKfMpArnGNtKhf9h7dF9xJo/azOPir20LC8X+5+IyhPYOS+igxuarUv6FJNEr27CFkMcH4sBjNEKd2PZkaJn+VxGsknEvkvn1PksAkS+sJ382GI0jvav16eZJHBcDX1umRBJssIW0/kcY0VWfyRY8/bzEYLLnupG2eBLEuVzQ68TCciRDufCcinppzcXNO0K2LCxkTQ==
    - name: argocd-initial-admin-secret
      data:
        password: AgAXEV0tinFGJth3z1szjtRK1Wor+BP26AdeEGjoz6pWNYRExyln6jNylBngsYGg+A51ZTM8fcDjY+UY6hHXFDFAxt3QfIQ3vd8VAIU/Nb0BhU9Z7VsTdlCQiYjh4AL4mYqazP2b7ElQArH38/ppv1MpC8/vKUxD96UDri4VOuHkujeUZ08felnGIHQBStQnyL3jkacwW9JRgSXcvG59KUR1g9N+PIS4LJLBAiAUp/lABMrrohxsb99G6ZVep95P4CgHT3VNb9QAF6Qba1ybWzwGWgL/A4gOuukMGu15Nqw5B+ufnGf14IOach58f/s6EKDziR6nK+de8c+YVIOkN2W/EKPnzt/E4gI++oNuhHDpVLK1WwKnfo2fkFFHWfFxfe/mvepMtJrEbhBRsnp6lbEbEg90VHjjg8pahCngt1jZCCIh643UCIIljoiVMfSV79fJ+LfAbJXBa7bVJk0IVIS2SB9JmN06WwVKr9jCwaLy5JrF74zFZLp0UDQS+jq3CRVhFAOpdm5fGKshzn/i4NAWaYi0zCX6xgQOxSLvqaQH0GXdRjuC4EZsnwqBSSRWGwkhuGxxUZoMWrN2bZqF6DYZcWGRLaNZVba5OmgHMZJVLrCf0rdIHDNuCxIlql1RrC1TfZ9wU5tzu8XamJ3F6fSNLecQf/jowR4tpqjSu2Vx62YF2usRBy5cPqPGJ+sGgRMV+1m2Ic9mBLGRuBWhhFAg

  securityPolicies:
    - name: argocd-public
      targetRoute: argocd-public
      extAuth:
        grpc:
          backendRefs:
            - group: ""
              kind: Service
              name: homelab-envoy-proxy-bouncer
              namespace: envoy-gateway-system
              port: 8080
