argocd:
  global:
    domain: argocd.kyledev.co

  configs:
    cm:
      url: https://argocd.kyledev.co
      admin.enabled: "true"
      accounts.readonly-user: login, apiKey
      statusbadge.enabled: "true"
      statusbadge.url: https://argocd.kyledev.co/
      application.namespaces: "*"
      oidc.config: |
        name: PocketID
        issuer: https://pocketid.kyledev.co
        clientID: 7e697ce9-a9ae-4fae-9782-bb2f575d65a8
        clientSecret: $oidc.pocketid.clientSecret
        requestedScopes: ["openid", "profile", "email", "groups"]
        requestedIDTokenClaims:
          groups:
            essential: true
      resource.customizations: |
        apiextensions.k8s.io/CustomResourceDefinition:
          ignoreDifferences: |
            jsonPointers:
            - /status
        admissionregistration.k8s.io/ValidatingWebhookConfiguration:
          ignoreDifferences: |
            jsonPointers:
            - /webhooks/0/clientConfig/caBundle
            - /webhooks/1/clientConfig/caBundle

      resource.customizations.ignoreDifferences.all: |
        managedFieldsManagers:
          - kube-controller-manager
        jsonPointers:
          - /spec/template/spec/containers/0/resources/requests
          - /spec/template/spec/containers/0/resources/limits

    rbac:
      policy.csv: |
        p, role:admin, *, *, *, allow
        g, admins, role:admin
        g, friends, role:readonly
      policy.default: role:readonly

    params:
      server.insecure: "true"

    secret:
      createSecret: false

  dex:
    enabled: false

  server:
    ingress:
      enabled: false
    service:
      type: ClusterIP

    httproute:
      enabled: false

homelab:
  httproutes:
    - name: argocd-int
      hostnames:
        - argocd.int.kyledev.co
      parentRefs:
        - name: homelab
          namespace: envoy-gateway-system
      rules:
        - backendRefs:
            - group: ""
              kind: Service
              name: argocd-server
              port: 80
    - name: argocd-public
      hostnames:
        - argocd.kyledev.co
        - argocd.ts.kyledev.co
      parentRefs:
        - name: homelab
          namespace: envoy-gateway-system
      rules:
        - backendRefs:
            - group: ""
              kind: Service
              name: argocd-server
              port: 80

  sealedsecrets:
    - name: argocd-secret
      data:
        admin.password: AgAzm5pwGtt2yA40b9ADcsVwUnK64uaTfL7amk4cGFuk6m8d+s5aFXTazEgl0dYXqULGsKxZ7lsQEZKaqb1cqZFscIMO5uT7wd3AQVMxNu6gKjAb8JhvC38qJngZLM6SBy6uDPuzkXh21lS/vLcrvuZadq3Kst05vSKJb2jCpK4HTNEuoCRXMox5oLx1HAzskFhv7zkaXzefMPmKvf2ODKNXgjWUx+U3X6odng4Qa9Pv3coW+Of1yAwJ45xWaPCT2fjl5L0pWnPWs88Iz+jbvistotkEZWh+hnWhyoxtcSnCQZh2mdKdhuLRLOl4uiEUxrUKC9m4IzsST2QpjgZQFpEf7yZE47uJh2uXXuNPyFXRBl/AikizPMCRXyrfyo9lU48wqqyay98EyZRzFzU/0+VWwItAznwYm9ZSe2GHwsjh5M751QXLSpcC7nIDQ539/0blWIsMXQbFAOhUKhkzWAmVenrbpfhKnaifJiHYuV17Kxf4y3TwQ74sE1EPQCDg6WCgZ55zitQ4mYVwtPTphHrBU9Ex0oE7Q/Z/OsIay2HnUHJmQUlIU9TXsPgUQdpJsXm7HszMJyBX/WkX3Xa+RjIlAuiAmLDVnyqYi5yg/w2Ka8FH4Lmq7W6G0vl+xDwK+hE6HJrqz6utOad+i7Ab+N9n+WB8kURFG3SRDcphQcG9MOp88exJjz4U/w7qkDWCiWe+xRuK09XT2msaQ6r9GCsojpcRHA0lPtcVkNwmU1xlGw/aRg3VLos28WouLjgRa2F7j2g7RBbLt4P5Ie0=
        admin.passwordMtime: AgBbvCFUcvI6sec1MKCIjEois+ViVq6lka+AsF82Y8GxXTsyZV6KerQBmEYS6UVrjAqG4RH3xQFxlgv7tFrQeAhfi3Ixng10xGd4Dm5RXbhH4YBLPpwCkV9Q6Xi6JKmlYQNYbayEfI5Ss1k9HmToUhMN1FrgxipxiV2oZjbtuBwS9mkSAH67FJYb4PMTTg+oG6tfLmj8BWtYdF1pooCwisQ8R2dc4ow6XixAVn0WhSyDBJ/tgCF7llbVVsem/8VDZ3XvoUF8phb/r+e4O2Ag6CkWrEIcrIsO3/JzZ1Afi1Aa/wYPHcyIBKbtS72cVk633FetS3u9ryuZuaRTjmgDhz6VeXyma6zzA1JMtU+1GfDsQDs00nODh9peKHhCaIt8Ag4ByV0GaJ4bHsfjXwtQduq6jHAatZz+zkY7MNbWMplevtEZRNec/sBlfFTMb7k12MYo38An/vyDOdv6zeSf411Jukbd5B7+A/9+kFz1QFBNfd8V2C3A1pD5iF5qMPsb36RAnK5lX9Wvk7/VeqYzjrrKovrNE8c0JsxG8sABhHBlOuohpG+4YOuAP/a7h2sgDLjynti2F+ezVvxG46ghCxazY7SVbw145Slm9wXflCzq6S4YoUSqFInZQMPaH1t0LjGvLAIs16kj9k+CxVLx42NbjitbLI7G3jnIY008HDavXOUssGXS7fEPhGRlV6qrwPrNKEYkY7w4uFQab81Ug3sIwX+u+Q==
        oidc.pocketid.clientSecret: AgClcv9bzF5W1wrAMUPEbGv75B8lne4iTbqhGrKew8B3tT+sHAAc2+EP5tqUxKwPmGUCdLkXwtRdwWWG3yPf482sEJ/OhYLjmIFWKKXNA9+wr9GRoJNnLadas8KpT49B8wxnxeFK1tzUuZPJUbvSEBFqBQDRm81JbGPeD08nk/7xymf/PUo/l8gaAFG4xr4HCic9M7Weppv+JYMjnweiETIihpiAazoT897OfgaagbqWa/F9z65Jo5aGSq67IAi6kJ0hD0M/lTwLGudcrDH/syT+sP0Mow0JYS94TUt3vZTSvKnsp57RjbLTMIjpmg8UgxfEUm4iefscYcj595YEq2BWDsF8aqjR/sLWmccgEjM78XFesbonausakc7R7i2k/VY3F/Sy0ZX3VXU7bXCxHd7lKLbSRQ+DYkwXZVLszrUwvsyiYgm1GGJj10OGQTOHb2dv8BZvfrFvFJgM5pB4iAuf1GcsafPooLov3hns1e04+54a9ON7FTiz9dfG7g9ttn848lDlCTcOxy9/EELaK/m5ZFNq4KCluhhfwXc5oq73ZK/YtCS09TN15s45z4bC8V/b75g3ZGKE9g403mvVqFJ6M18GDE3ZEPIrS0fnxDwzAdP2l2Uu2M5rUbYqbMlIu0PBV6XThTU9jjUaMXWpFtev5E7o1ZlEmA1uN2ZpKRFKiRokKn2VxSHC6ZXob21Bhx1iuzpAYSUUjvNGJeVsriGyqn3BFOTWyedbFqrVr8R7gw==
        server.secretkey: AgCXS8rOTRaDzhxvt4RHUHQBOR/uP+Dqungmq/jqjW5DAIi44+hVLL4lwlKYrE7QV96ZvqPE53yH4Ic/UMpNLcYVY45mS+c7wOX4dFpFYOduQ+6WHDLuQ5bXfYKqsDCk1zeIq/HwpGyEtb4VRCrAOBKm/IiEhYESXAggKALKtiJJJOL3X3+l/XpNoPO6OjcscH/c7I6+y6A5GJIGjjlsAT/e+odTej0psrihIKfzitvuMyVIHzEIHOz9L+/vSislGMAMpi7jQ4H5cD48m8IRxR6/AEvfBHBLfpWIMifMOpnfV4zb2Oxl2fV5CbBAc5Upvt8a18s+S+TYtr4GSjMNMl29GFElqur7lNjO3MU2NjrH4Y/2+38v12d2TqVzejSf24qcWn+GHu6zYdSOAQWLIQMC24vio646IGLaRtdf41db+mkHn72nJ7R8j0p/gO1HGQGZQlz6rBRMFUJdSBYMecov3KmFvb3JPM9nKUNuhCJZLkeRicEq9v/Gl4QHwhdIF46HwWfCDIW1gdB4qBatBDqF62hZ56TFP8kBTbPGp/0quTHo0SgFpCw93Yu8SeAWYl3E/BSmDpFlLwfIlcHjlAcnYKVGQzbP2wGcZd4w4TcnVHESttoAb6/za+ASV02snSTvPmZU8hv7KVf9IhPXlz5RytFWYaTOby1ttK0zQUsl23iYbXQMVrkbfMKVYBrLf1LQktzRz69pdNtyWGCKaZuSqkvK+2CGuI0G6fGs/5zXGyaJpp0ALBEJU+hDNA==
    - name: argocd-initial-admin-secret
      data:
        password: AgAXEV0tinFGJth3z1szjtRK1Wor+BP26AdeEGjoz6pWNYRExyln6jNylBngsYGg+A51ZTM8fcDjY+UY6hHXFDFAxt3QfIQ3vd8VAIU/Nb0BhU9Z7VsTdlCQiYjh4AL4mYqazP2b7ElQArH38/ppv1MpC8/vKUxD96UDri4VOuHkujeUZ08felnGIHQBStQnyL3jkacwW9JRgSXcvG59KUR1g9N+PIS4LJLBAiAUp/lABMrrohxsb99G6ZVep95P4CgHT3VNb9QAF6Qba1ybWzwGWgL/A4gOuukMGu15Nqw5B+ufnGf14IOach58f/s6EKDziR6nK+de8c+YVIOkN2W/EKPnzt/E4gI++oNuhHDpVLK1WwKnfo2fkFFHWfFxfe/mvepMtJrEbhBRsnp6lbEbEg90VHjjg8pahCngt1jZCCIh643UCIIljoiVMfSV79fJ+LfAbJXBa7bVJk0IVIS2SB9JmN06WwVKr9jCwaLy5JrF74zFZLp0UDQS+jq3CRVhFAOpdm5fGKshzn/i4NAWaYi0zCX6xgQOxSLvqaQH0GXdRjuC4EZsnwqBSSRWGwkhuGxxUZoMWrN2bZqF6DYZcWGRLaNZVba5OmgHMZJVLrCf0rdIHDNuCxIlql1RrC1TfZ9wU5tzu8XamJ3F6fSNLecQf/jowR4tpqjSu2Vx62YF2usRBy5cPqPGJ+sGgRMV+1m2Ic9mBLGRuBWhhFAg

  securityPolicies:
    - name: argocd-public
      targetRoute: argocd-public
      extAuth:
        grpc:
          backendRefs:
            - group: ""
              kind: Service
              name: homelab-envoy-proxy-bouncer
              namespace: envoy-gateway-system
              port: 8080
