argocd:
  global:
    domain: argocd.kyledev.co

  configs:
    cm:
      url: https://argocd.kyledev.co
      admin.enabled: "true"
      accounts.readonly-user: login, apiKey
      statusbadge.enabled: "true"
      statusbadge.url: https://argocd.kyledev.co/
      application.namespaces: "*"
      timeout.reconciliation: 180s
      timeout.reconciliation.jitter: 90s
      oidc.config: |
        name: PocketID
        issuer: https://pocketid.kyledev.co
        clientID: 7e697ce9-a9ae-4fae-9782-bb2f575d65a8
        clientSecret: $oidc.pocketid.clientSecret
        requestedScopes: ["openid", "profile", "email", "groups"]
        requestedIDTokenClaims:
          groups:
            essential: true
      resource.customizations: |
        apiextensions.k8s.io/CustomResourceDefinition:
          ignoreDifferences: |
            jsonPointers:
            - /status
        admissionregistration.k8s.io/ValidatingWebhookConfiguration:
          ignoreDifferences: |
            jsonPointers:
            - /webhooks/0/clientConfig/caBundle
            - /webhooks/1/clientConfig/caBundle

      resource.customizations.ignoreDifferences.all: |
        managedFieldsManagers:
          - kube-controller-manager
        jsonPointers:
          - /spec/template/spec/containers/0/resources/requests
          - /spec/template/spec/containers/0/resources/limits

    rbac:
      policy.csv: |
        p, role:admin, *, *, *, allow
        g, admins, role:admin
        g, friends, role:readonly
      policy.default: role:readonly

    params:
      server.insecure: "true"

    secret:
      createSecret: false

  dex:
    enabled: false

  server:
    ingress:
      enabled: false
    service:
      type: ClusterIP

    httproute:
      enabled: false

homelab:
  httproutes:
    - name: argocd-int
      hostnames:
        - argocd.int.kyledev.co
      parentRefs:
        - name: homelab
          namespace: envoy-gateway-system
      rules:
        - backendRefs:
            - group: ""
              kind: Service
              name: argocd-server
              port: 80
    - name: argocd-public
      hostnames:
        - argocd.kyledev.co
        - argocd.ts.kyledev.co
      parentRefs:
        - name: homelab
          namespace: envoy-gateway-system
      rules:
        - backendRefs:
            - group: ""
              kind: Service
              name: argocd-server
              port: 80

  sealedsecrets:
    - name: argocd-secret
      data:
        admin.password: AgDEAfmND+6I1hGNvR74Ov1pMpT/XwwQjfcwdnZ+PXqY7oAg6n6Tu5Gxe/Jx8zqB7b6uu+73rKs3/drjCEbdL6ogqg8fz+AlgpRGwHCxtYUj24jmYRaMl+UmI7Sb2XNZXXS1h2Hu2AMpATuG2iRnuPEn7ie4A+7m3w41aY40BkC1CBvB9prqTPgd0bGML2/l0u9BmSCi9G4cPuVYejmmQ9FMK3W82yrbipaj0xgjBHr59/FmtOtZa5DK9uogvI/TL+LsYSqK18qeip/eIiH67bHfzn0bQKXmYZ4NF2pEvNR8Za8bCBI0dJU2+5snPdjIk5N4NsmKJeu4qBPYtOu0vktS0aA5AcxUStPgzKYNKnXqMYCODPK1GA3/1anIlBxyli4D2/z8eSLAmxirWlJIj229yC15WFKLQYcPiwwtG1Tjb9d2UW1MVAdteTeZ1WRnN/BDEv48Bc0xvRLPZtbrzi3Nr4QhQvNm68rQZk6B/sxIxvGy6z8OM57lJ8RSfJ3Ar9BHfnT8qxV7KPidPLj1Nx06JNn9WsiLq0qTKBgtd9NLniNkS3lhVnqobgCbALhr8Qr66tZqAoYcWn9CdJJUpUvXyaIgAniTPjEijt7IwTPgV5t2r3n5DeSk+nHWhrT4p2ZvEOkaqRYcYh1zvWNncuWr1pwoBm455WbrYymZEwrJoyfvO9V0HcvMzH6GjWcCZCgDm5ihPqiQQsfovtlnjuEQkWekZuqZE2LicpIz1Y57Wm3NZkzsWIbpwA6cGzYOfHpcKV6zNP4Db7Ztllo=
        admin.passwordMtime: AgClUYNtjiHsqJYgMQMTnezPEsvLkD4Q0eT/SaO1gYva5uhkVwKpMiQV25h5HxCzZu5MSyKBTVvbDWQjwoWCh/FGcXu3DGXyC/6KN8zN6t5UP1xHRm848os1kT1zYKkwckpnHVxe555W+7PL6SnbWP3JQl5yE6hNrNRTcQKdFnD0uD9WMALehLm3V6bhr/4IH3ulKXHAsUD6p2QtPk47eQMFRL96atJoH+zpCj37sn4U61+tuH8Ry2Wly4ui6TOPUY5PpikUIcilfVx1mLTqaGP0shOMI7WYbl1jdnXSGL9oYHcQUyF2Mc6/hydDHtn4WQoMxM7LkNJeV5RthHd0QvlAizn0VzDuaBCNdQxx/8JtDGfYaQ2zM+jr+bB9rJYFBfU/Jk6tHsMFigU70Dwgo7kFSYHGa3nbFRmXp34OCc7FeMAZrmOTZ/rCYcRiSIpGTPygCNbHpYb7DeB16+QA3gHsW3TC+SU2ktkAuWr6NkK/hsPXXp4iffvVmdUfdvU5zuaYtjorgxk8AtwfhJHb4EFGmngyhTN8Je+JcOwQwQJJP4xwsAOY22TyHZ2BZatINZcGky8/5e36xTdV0qD2LrN1002B1npCamrot6KyOMDeQsEF61GuvpadAINk9E4InDhclG8HtLLMBqGyJ4deYaqzQcwHNSUbVOIIfbwo7rhhijGo0KczCeqyJLOc6GrKkfR84AKMdooQLFPuKKB3JteR//Itwg==
        oidc.pocketid.clientSecret: AgCq2EPNcy7jq4xrRQRkPxNRpA0VQEnswuHT+u7G3j+jIdmbb2HrG1hhEC1DaDzpgvsrZazMcOfemgqT2rU1iHWQ2u3xSeDAJtHFRAi+V+H+GJlkODUtIXefpjjXXFHXGYH1cmB5UvvNMj4i6/Dn1wSxfNRCt4J1wP6x5wTjS0xQCzbh5ezTdSG1biAhXYZ+KD/YtUAFN0aXU451MY/YM1GzzmIGDmuRsag+ytf073ltdhqmqpaoc5NZYZte2BgneNdKFbPAn++PCxSYJg6VdTc0WGuVItA6q65P1RZqDLGYojkJtJidWsQ8nAvm75OYFjSXubvHxggUPiEX2TP9xYqjjkS2rnBkzsRo1Ke9pwQvNVTS+S248RWeBf520Imim3unCpi3Aj/kYi3rn3ypMFFs75AJzUiV3+iNxXPUH791IdpNAe9X12hhLKShq+8swfjODEiY15uK11lbWh+zwK/vLPgm+ZldhjxrB6WlIvgc3IYuaoWy303Iar+9kZYLQMqxi2jmM6kg8GD6RVGbsRYfmIg9grOzAKrR/RWtW89Ix/OTiU9F9Q5XIHClR4j2ivKyyq3/4STXncC9qY9WFaVctffrKQvPLKc2iFNudiNsa0sfnh/u+hLl7Wh20mACGjklXzoHyv43UXz/lHSLxOpfsy5xhgTwevShSU9gXedJ9octwywyodHPd51G8qoap+CR02L/TGC+owMnPlkbwoWZtFHvCNcJEHzYs1kebWS/JA==
        server.secretkey: AgCGviDn6NBfgeNEFjIUuOQqkpRbPndWuhKymtupsTaOMibppNOqQNhwQmgb9+1qC2pBApObkJH0y/I/OnY+bKx0H3YV01+LWAAr+3YGkRzDy/IBaD6AKl+DN73fyeKciBJiGtw9XDrQIVAgpwd0pm0x/NUeaNGRMmSxDnt9bPGq/Q6gDDjWRZuj+OxaqKkBb80ZKj7UoUxz+CKwBukTM4Wiwt5cjuBudDPq+MzY4MPh/Nxbjp2arXr3uN25Ab9RWqqvojq7XhcQiu9/2t05TZIxInLftMWKwYPCp/q2OxUiUoxkxBB1+OjVva1mInVfGrmoRM2/csAKB0MX+Ar0ukpLZd5R6soq5Udas9A9k/2aN3LeUzFLRJlIgwuYqcvYWLaz0elP541U8cNniS0RjDMCuHbHDjYxappCuC27GbFoSn7Ygvyg7g0CFzfjIkCcRAUcKDaoP4UgXAozli1IpuwULVoUNidYp00KsWqwkl/WBFQWH24OGXKG9gy2zVtRWL77EmFo6r1LiREz9XK1rfxNS2KKGSpZEYK5ld2iom93EmMLglt0MW1DtOBzFNgGNwefUfoSLOVvjRtst+cXYsfzkVGeTAS1G9GFQbwDXEZxqI8L9U92Biqb0Fn1UcimwsqH4mXliX9AnS0bTZCNhycEGFCrbISmAWJdNiQewYTHdlmRihQRzA6Bhpv5bwp59x37B+FzxDopd607WJsGiiRwZ5sKVKB3W2GBSMbNdoTGrR7i/6vgm6mC/t71JA==
    - name: argocd-initial-admin-secret
      data:
        password: AgBpy5GxQnUpCUpY6yNri0+IYHhLlPjYnLWl1srxvdH+YxzzznYB8gpcL0Q2jT8z6ji9ZXpbjwqZViolOrFLSmq9Gdxt1Sew9ZF3foP2szciM0AqaqO+Wskv1V38BIZ40+K3EgBAU2NKoc5Zo53wSLZ7JWQmEUV2450hBQ6RKKseymGVKX+5bZgKFrpZ7kQun4UIlhUIe0zl3T9JDThXXSMmhuDuh3ZsNxPhlck595HplWKnUUCrddHwwug1bFXuQT1onhN45hpdXBWU8xdYkPC/jY5bRUlYLb7LLJ9r5jYX/O0jBHLrV3fnt+m08vgzIo+QKpLQ4iaJxdsQXFsYGRFY1vexxEkTICKZ8cRaAlbX1NbT7X6FUVXms2+lbKZvn6NhJquOPm+mhrBQNSNgs1HM9woPsDRrwsKC3tbOMe+mEawHeMTFwAKr0+raWkf+zZB169VdcnLt83XboHvSuCaxwMriiyl6alLKJTqF3/0HhohQcQ28H66DqUB18UI3P0l8Bzh+rqq+rcjrBHDZEyb00hyZRX4KqKO8+y5Qc+cbwAlK7ig0D/pW3G7wngz18cWMdlgSovfkdsqBwTNNyTqnSK8Y+Lv//EbERIKpeNd5uz0O5m2gBRguuRBxRLIj0NrQAFy/fNvZAPAbSG2pTv9CqeVJuGE9OJIqsCU2g2218Pm3v/fexAAaJ/Pgud3d2hyAfWiCMP9PfGmmAzcK0yYq
  securityPolicies:
    - name: argocd-public
      targetRoute: argocd-public
      extAuth:
        failOpen: true
        grpc:
          backendRefs:
            - group: ""
              kind: Service
              name: homelab-envoy-proxy-bouncer
              namespace: crowdsec
              port: 8080
              weight: 1
