apiVersion: v2
name: nats
description: nats with homelab-chart
version: 0.1.0
dependencies:
  - name: nats
    version: 2.12.6
    repository: https://nats-io.github.io/k8s/helm/charts/
    alias: nats
  - name: homelab-chart
    version: 0.1.30
    repository: oci://ghcr.io/kdwils/charts
    alias: homelab
