apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: kube-prometheus-stack:homelab
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: "https://kubernetes.default.svc"
  source:
    path: monitoring/kube-prometheus-stack
    repoURL: "https://github.com/kdwils/homelab"
    targetRevision: homelab
  sources: []
  project: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
