---
# Source: homelab/charts/baldsky/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: baldsky
  labels:
    helm.sh/chart: baldsky-0.1.31
    app.kubernetes.io/name: baldsky
    app.kubernetes.io/instance: baldsky
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
---
# Source: homelab/charts/baldsky/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  labels:
    helm.sh/chart: baldsky-0.1.31
    app.kubernetes.io/name: baldsky
    app.kubernetes.io/instance: baldsky
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
data:
  config.yaml: |
    server:
      enabled: true
      port: 8080
      log_level: info
      hostname: "baldsky.kyledev.co"
      service_did: "did:web:baldsky.kyledev.co"
      publisher_did: "did:plc:4rlgcneeu5n4jdnlfwljdf2j"
      did_context: "https://www.w3.org/ns/did/v1"
      service_id: "#bsky_fg"
      user_agent: baldsky
      user_agent_url: https://github.com/kdwils/baldsky
  
    database:
      dsn: ""
      reconnect_delay: 5s
  
    subscription:
      enabled: false
      endpoint: "wss://bsky.network"
      reconnect_delay: 5s
      concurrency: 4
      queue_size: 1000
  
    pipelines:
      - enabled: true
        short_name: bald
        display_name: "Bald Things"
        description: "Curated feed for the follically challenged"
        collection_name: app.bsky.feed.generator
        languages:
          - en
        link_label: "GitHub"
        link_url: "https://github.com/kdwils/baldsky"
---
# Source: homelab/charts/baldsky/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: baldsky
  labels:
    helm.sh/chart: baldsky-0.1.31
    app.kubernetes.io/name: baldsky
    app.kubernetes.io/instance: baldsky
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: baldsky
    app.kubernetes.io/instance: baldsky
---
# Source: homelab/charts/baldsky/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: baldsky
  labels:
    helm.sh/chart: baldsky-0.1.31
    app.kubernetes.io/name: baldsky
    app.kubernetes.io/instance: baldsky
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: baldsky
      app.kubernetes.io/instance: baldsky
  template:
    metadata:
      labels:
        helm.sh/chart: baldsky-0.1.31
        app.kubernetes.io/name: baldsky
        app.kubernetes.io/instance: baldsky
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: baldsky
      securityContext:
        fsGroup: 2000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: baldsky
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
          image: "ghcr.io/kdwils/baldsky:sha-9bb83b7b699cb1be41702fa82a1e2ee3c2c02cc2"
          imagePullPolicy: IfNotPresent
          args:
            - serve
            - --config=/app/config.yaml
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /xrpc/_health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /xrpc/_health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 128Mi
          volumeMounts:
            - mountPath: /app/config.yaml
              name: configmap-api-config
              readOnly: true
              subPath: config.yaml
          env:
            - name: BALDSKY_DATABASE_DSN
              valueFrom:
                secretKeyRef:
                  key: uri
                  name: baldsky-app
            - name: BALDSKY_SERVER_ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  key: adminToken
                  name: baldsky
      volumes:
        - configMap:
            name: api-config
          name: configmap-api-config
---
# Source: homelab/charts/baldsky/templates/postgres.yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: baldsky
  labels:
    helm.sh/chart: baldsky-0.1.31
    app.kubernetes.io/name: baldsky
    app.kubernetes.io/instance: baldsky
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  instances: 3
  storage:
    size: 50Gi
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
  bootstrap:
    initdb:
      database: baldsky
      owner: baldsky
---
# Source: homelab/charts/baldsky/templates/httproute.yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: baldsky
  labels:
    helm.sh/chart: baldsky-0.1.31
    app.kubernetes.io/name: baldsky
    app.kubernetes.io/instance: baldsky
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: homelab
      namespace: envoy-gateway-system
  hostnames:
    - "baldsky.kyledev.co"
    - "baldsky.int.kyledev.co"
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      backendRefs:
      - group: ""
        kind: Service
        name: baldsky
        port: 8080
        weight: 1
---
# Source: homelab/charts/baldsky/templates/sealedsecret.yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: baldsky
  namespace: bluesky
spec:
  encryptedData:
    adminToken: AgCiIm5ym81EIsxdjZsWqDnPaQj0DXMmI25+LnjRPisqEhhNZk1xasCKjh8mN946c7fk9WxRzjwKYMZ993wppPflnLkRS081yG4bVbH/O8QRsaFiQl73A2uQo72ZdeXofGyFmNQtp46AF2saN210ZDXDECh0U92SoOZOd+j0gsb88Vv3fmLX9I8w+56Y6H213tMhXYdbBpxmrGFSAOgtbfAB7x3UxYnWoLpxgWePZwOv4xenq1jVYapsBwCLXRoUjw16h15l80WzCZVJiJ4P5IGzZf3vWvbrZaIBmjP2Ctnd+yfjGEfQCeLneO/jvMwObNyT33xAwJEJeEBaw26riBUY4gIM4L9FZRtiAr2vQjU+/msWjH3u6Nwsx+xxRVmIS1xqoVFezXQD0a15bpwNYAFRmbJsnob5feFrSilpmdL3Xq9BE7Y1iNO+vq4BD9OGVIy4G/8JY7W11ISl9Vd/QV4fe7kLo9ovnF0Xw9dF/MFhvAAbiLtt7IDINFxwbHAK1NUztVUkXqsv8CrsBsB6o2MmWjmdYvgU/65OfepH3jX9A18izuajaPZgldo5wCbMb/yBVnvxtudrqmHKpCvIQ54njVvZ9553qOqpnxV0GiSW4i4hOP643hIHrzrkvgl31f3zl8EQJth/SQk+LRgo9HU9nharWAVu6OAdDQTO9x4fz93NsRhpDfR5MU+scTRHWiQZdvmTTp9bg42pgR2K7wB+qL7Qr+MM5NoK7tlGPlkl4ZQXpbfPcxiGu9TcyA==
  template:
    type: Opaque
    metadata:
      name: baldsky
      namespace: bluesky
---
# Source: homelab/charts/baldsky/templates/securitypolicy.yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: baldsky
  labels:
    helm.sh/chart: baldsky-0.1.31
    app.kubernetes.io/name: baldsky
    app.kubernetes.io/instance: baldsky
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: baldsky
  extAuth:
    grpc:
      backendRefs:
      - group: ""
        kind: Service
        name: homelab-envoy-proxy-bouncer
        namespace: crowdsec
        port: 8080
        weight: 1
---
# Source: homelab/charts/baldsky/templates/vpa.yaml
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: baldsky
  labels:
    helm.sh/chart: baldsky-0.1.31
    app.kubernetes.io/name: baldsky
    app.kubernetes.io/instance: baldsky
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: baldsky
  updatePolicy:
    updateMode: InPlace
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      controlledResources:
      - cpu
      - memory
      controlledValues: RequestsAndLimits
      maxAllowed:
        cpu: 1000m
        memory: 1Gi
