apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: coder-db
  namespace: coder
spec:
  instances: 1
  storage:
    size: 10Gi
    pvcTemplate:
      accessModes:
        - ReadWriteMany
  bootstrap:
    initdb:
      database: coder
      owner: coder
