---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgA0w6M3gZvoY32vs6/dzdwTbQk7App87mKMrsAv9BQvVZrKvZF47LbogOyLwdNjez9+kUV+IAgibml5VpK9pcG9sRE2NrH8JIiBdXA+6lVY2UgakveHZ/7tEnnC5PXw0rfJuZ2LbcQ/dfwOOrZIOXbkYPKNUTwJttjR56d0cZrNvJ4n/56d+3mVXMF5lNQFVIh15gY/ijm7FbYua3dPrXH5DWaMIar4lxEF1Gcb4FUNgo0iecR5QRvOyiGmWAKZ8frbeIqNrH14slbQLCyCZSB9IrumcNxWF68Dm91sIBbwXiplptTeNtxflVS3yPce6vIW0kcmO1ZJtXLRvZuy0KolaDYQGtimNG/iswqpU4noZrCBKbXUCx1rDZtnpG8mMjo+fdHsK6lbTrUtOyyXINjcHV4pwlqqmf9RFrRtpBRh0wh1MDfgW0JdEpnDPOKfvuejYE6UUkqqx8yRjmdiuzrUYq6uXVUSP+Eqg0ADZCVaUZympZugZeT+UT5xRJhgSoV+5Eoj7k/MgBOJY+cbMnEWWAVIAffCBN6mlRCtCy/RKp32o8ji5lvB+ohkQXwl3R1k6eYDcVJLF8kB2G7R+zvKenh4821MOMAo6TvyYzTBiMxEvGGlq0wehYX/2QL6EnShbp1P1GntzprajdLySWv4Qa9Z8L+Zdbjdvodaghc6nA3NksXSaPA8wxxGJwqWJKotDg4yBRH2GhUrgLvYKgyqnbH4O8TcbBO59zvKK/WjD7Byop/QIMoE
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
