vertical-pod-autoscaler:
  fullnameOverride: vpa
  rbac:
    create: true
  admissionController:
    enabled: true
    replicas: 1
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
      limits:
        cpu: 200m
        memory: 256Mi
    extraArgs:
      - --feature-gates=InPlace=true
  recommender:
    enabled: true
    replicas: 1
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi
  updater:
    enabled: true
    replicas: 1
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
      limits:
        cpu: 200m
        memory: 256Mi
    extraArgs:
      - --feature-gates=InPlace=true
