vertical-pod-autoscaler:
  fullnameOverride: vpa
  rbac:
    create: true
  admissionController:
    enabled: true
    replicas: 1
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 256Gi
    extraArgs:
      - --feature-gates=InPlace=true
  recommender:
    enabled: true
    replicas: 1
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 256Gi
  updater:
    enabled: true
    replicas: 1
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 256Gi
    extraArgs:
      - --feature-gates=InPlace=true
