cloudflared:
  serviceAccount:
    create: true

  deployment:
    create: true
    replicas: 1
    image:
      repository: cloudflare/cloudflared
      tag: 2026.6.1

    args:
      - tunnel
      - --loglevel
      - debug
      - --config
      - /etc/cloudflared/config/config.yaml
      - run

    livenessProbe:
      httpGet:
        path: /ready
        port: 2000
      initialDelaySeconds: 10
      periodSeconds: 10

    volumeMounts:
      - name: config
        mountPath: /etc/cloudflared/config/config.yaml
        subPath: config.yaml
      - name: creds
        mountPath: /etc/cloudflared/creds/homelab.json
        subPath: homelab.json
      - name: cert
        mountPath: /etc/cloudflared/cert.pem
        subPath: cert.pem

    volumes:
      - name: creds
        secret:
          secretName: tunnel
          items:
            - key: homelab.json
              path: homelab.json
      - name: cert
        secret:
          secretName: tunnel
          items:
            - key: cert.pem
              path: cert.pem
      - name: config
        configMap:
          name: cloudflared
          items:
            - key: config.yaml
              path: config.yaml

  configmap:
    create: true
    configmaps:
      - name: cloudflared
        data:
          config.yaml: |
            tunnel: 34a29bd3-c367-4439-bc8d-32a6dbfc98ff
            credentials-file: /etc/cloudflared/creds/homelab.json
            no-autoupdate: true
            protocol: http2
            metrics: 0.0.0.0:2000
            ingress:
              - hostname: blog.kyledev.co
                service: https://homelab-gateway.envoy-gateway-system.svc.cluster.local:443
                originRequest:
                  originServerName: blog.kyledev.co
              - hostname: argocd.kyledev.co
                service: https://homelab-gateway.envoy-gateway-system.svc.cluster.local:443
                originRequest:
                  originServerName: argocd.kyledev.co
              - hostname: mealie.kyledev.co
                service: https://homelab-gateway.envoy-gateway-system.svc.cluster.local:443
                originRequest:
                  originServerName: mealie.kyledev.co
              - hostname: bluesky.kyledev.co
                service: https://homelab-gateway.envoy-gateway-system.svc.cluster.local:443
                originRequest:
                  originServerName: bluesky.kyledev.co
              - hostname: pocketid.kyledev.co
                service: https://homelab-gateway.envoy-gateway-system.svc.cluster.local:443
                originRequest:
                  originServerName: pocketid.kyledev.co
              - hostname: overseerr.kyledev.co
                service: https://homelab-gateway.envoy-gateway-system.svc.cluster.local:443
                originRequest:
                  originServerName: overseerr.kyledev.co
              - hostname: seerr.kyledev.co
                service: https://homelab-gateway.envoy-gateway-system.svc.cluster.local:443
                originRequest:
                  originServerName: seerr.kyledev.co
              - hostname: bouncer.kyledev.co
                service: https://homelab-gateway.envoy-gateway-system.svc.cluster.local:443
                originRequest:
                  originServerName: bouncer.kyledev.co
              - service: http_status:404

  sealedsecrets:
    - name: tunnel
      data:
        cert.pem: AgBDMM1aX01t8y/c2fjELfbNnJrXfFyot+N2aLIDJmXaOOScGboVWsnu1z70EEqdYQeY0f95sPAtItZbco1acH0BnZFvvoa3brFGUVtKX4/p1jozOeK3kel/358WKH0XyqijMFYwedkAiQTUWzwWOKGh3ZWg2dRT20zY0bG5vo2N4bSuaxHotBQTdfl8M4JIWjl+tZnt03fbnIBgm+jnxUZXGCLQ3JYkH6u0M9SAQ+hM1jwTkRWvgsKsR9J7zUJ2tbHMn9BfdPGXoPn4URPqS4GvCcITuI5ut2sxgEsx4HqBRJV+4bFU9CUPCgkR5PO6gk/Oj/W6kLIHxE8h1GDxMMKLFq21IqwDnXYpJI4kPKDgro9Wst4ZwpKq79nvgmvCjRbGkyXJzbyz8fRg2pq272o1EvszzUMHmzACzh1/rYP+nPcIeAN30RjLpqEo6Olqh3JT+ubxfuHueOwWiiVrYj2w7MATG9OQ9mGlHnySGmzqqBxIMFdoFQty0JxzhFJpObQFCcpBp48oSopOPeVm838sQi8/cKml9Sks8d2MaopEcyCMQceUx3HjxUPcSee0pbEVGdHvEL2OaX23wDlo7+rDex/qBG49YrIzArklWSOTIEi9wKfhXlXOdlu94cqr+iR2Q/YjtAJGRL0NuTAh3Op2LD/qseOoK02EZwWbcPt0aie3BQVADWTtGNaiKhVDncT/dmKTCsqMN7aU1nZmL7U4cokZpfGieYkU5hlpVxMdpmc1zzMiXu37jiyu+H6/k7YgUUttDhR44un11VKAMlC0472J4/WNm0RRotU6ZVQRhH3conkVCKlS0f4EruR4wZoe3broYH1xZ/Wt89lYzqv083R+KBp8vXtcD8UM5B6FcPo/AK8sTkiPXYmY8nQefJN2Hn7jmk25dpCLDeaJOTrqUd7H68ew03bh781/MU+zsnVxBtj4Lv9oxL6PKj99gIy4+UwxzQt0a79xwcxKVF4m5/kiucIW/XqARg5PBTkOX9+GFNbfLltxJWCdtGh4jLLl/U0sx0ChT4yUqjrHJ4+QmC+l7Hfrp/EwGuTz+Ot2fKJDsqMTKDmvlpsGvhah8aWT7nX2ElxhdRbe6PrF8QONq4YzUYiPrjdU5+PJceoVwAHIrIkniSGqNfKrijjt7a4WGw/eU5iRh/btJc1KNWjbfgKNXLWwrnc8Wfxg5vlgytoj9vyklLihthQvFgYsJJZr1/iGnTEpkoPsDZZBod9KEHXwyPJInHsvLNpLGJGXbDYROk3I5KW1VEehDe1f+eKuv4zYya+GsRCOOazfvy7O5Aax+7q7wVanNhCJcBaBIWJWqpqOwEQ3GWomNKkl6/LPWHw0XSEvANT7fa+4aoTyUPWYQCg4Pa6nXZEBYV/zVSaFSdJhVrO5fcYqFeiUuLf3zJfz0NQAjVWG7rQtmstIFLpMPSDBLBtXM1G9mDeP2CyRlruJWqN4jIGIvhOECeXMxsR7gKDlaWU79ue5uWauZahAHpFWbF5MNE8dTRbOVV4IBL59LU+Og1OILTpVOYeP+NER2svhiESurkRrA7yr48pVpq7DUxDPPV8SDT9jKV8+UD0hPOUfUSypJaeClmOP3tEF3jWMYb69f/6k3ywdnn84nATluQ2fxFK01LvL1gVLB3XWIeAY200ReK2KJRwH42jp1l9LB0EAzh9tudjqbocWljlkWg7G2/0965eFo9YT0HhP1dCAs/D0PHvums3IkN/ZZ7D0nfB99BQMQXpKnO/E5L0HejczWlv+uzG4tFwmXAImVB1gDiDFMxlpg3KDmA9DPs19WMNiGMcz8eyM15YPhvD9gwfNcrGUK4/lDvlPlbkkihRxh4jM+FV3LtiQCNkcSh2jUcHfaJybzmP3OezW6LA3re0n3pgUnelPcuw86XfFKVNLwNzdS+sE5RVrJuMFCVrHcql/Ne9ceXNJQUEiJgYOQQLSoZ7mdoVwrX5u8NkFk+VcjDty0BwGiq6MaT2yqoVOr8yQZvpKBNxege5CazzNZ1aFWa8l8fyTu5HkaBXYf9cqSdUWDPyNgSIBc0fFmTrJPtusSax1cCID+fbNwz//THjLE8k+HCmYx4MhVfOkw24GOwPRZy1fEna8p8tuai1DrDNWDTBqTsq8AQED+Us09+KcfTsetj98z8FvmXK1KksOpk/pTTAmP9Me2tTCyCgrHU+d1ovKj/B6LdbHb98KI8mTZ4VL0qnRrh+cwEyeMwiYiptBx+y07Nv8riE3YLzx2DY/HCzmyDWwFNFGr8cP9Stv8xrGbLVZetWQ3pD58jdl2TWDlP3wkEh3Y7kFpUmvzb0uLhq8aJaBC+lh7E9GIiu+zOiNV7rBQWdTzwBN8rv6noghBQusGIUql7eUEN2V9ij/5T9qMmKAAMKWnNnvBnkGe/4IEZ/bcBhVEQQ0z0RttJAmnam53dXod3m4mFHOV7gL0PgALdyYzyQahleK0PQ22GoZpTcRAFQdSBThcUSu7xeC0MroUCsR//PtJlP3zhNtOh/Iwht1UKrTEsDybZV3COwu+sMsLGhMAruukDgGD9YvCUBtK3j4/zz0DMcX6npADZupKs6sb8PL6kb6fVwTKefiiIKQ4Ipe8rg0ZI3Ta4yaxCpK5VA30oHjVxhIpq/cPgq+0q9f9VLU8PrkA821IILQMP0O/edNHqRRucNvclgeSg1FAS2cKIvbD7tzjXf4HEgXxgkuAbwQRXtxM9CSWPsY52e9PGs17Jb1a67BUjxHdcQynewIVeuwQyJ0AOwVWMz0ml0tuEiDuOVFhBihaZQM5aoPNLZUl2K+PwxDHTKkcI1sRPKhcwvAmp5kSkbVEhJ5cMmzv/3firNFJzzU2lIMtzW4m1hFtGgxZuw3ZvwmrNOENuNrRU3O4S0cPAVk01NEUg7hYy0DoKdiztxieGZJOG8zvXP/CkkoaegZYZp9WI04+gzUZhnM2kxCQUib3/HYtPcj6iLp7r7iAJXmeYrSaGU3V3wDFmxazSsGIoTw125nuxBsWWHLZ4jZWBgFQXDTAIDxbWgNaDj2bAvbiPRZ/onamMeUI0Fz5xheAa06yEwwQoQX7X2st7pHrHvuUJmXdJFOLcdBE8ugUHxwtcz8wcWGqEpns4D30Mx3YVBoEI0m2yql9TKCWvp9fc/Uxjf7aHv/oMOJEteED19NZUvCLg1C+hTsMVSLaA8mty1HtgQ7QdqMILSkoajrWRBnqJdbnCQ6YyUDOKtyh/SkE5dsyaN1HVJp4y7G1Wv7Hm+LZjFu9ahEEN4KaEVxMkcs
        homelab.json: AgAYYKX4dMhr8CxMsyn+2dsxhcR0EUmc7ZWEpy4DisU/PjNmitYM1dQapVJ1yh6UyG8i8lK9wV5qdwoD3IgI7XDAXMRkUgPPqufUNa4X3uEEIWAq/b7RPoJOigwiPh1F10uQZsXmNXsOakdsiQRSdaDGcxxITcyCQSYMNzCoB/ocyaXM/0XXyHugBFEIbxVmnFLn7LlJoUNW/Z1zo4Ae9CwnyT+579km9TX8zxY18UaiebaAyJ004Zqj/h0FVN2JISN7cB9qbyxB1owcJ81I062brbVUhz7Dm2Py+66CgAmzh/1k+aFkPHieAmuCsUOASJ8uZslQdq12D/wwPaxTDVr6NKB5NWqT+Eojru61FKNBiUs5Ddnq5A9t+aswFoEJcwgxgLuMc+qKKrVm1BiSs6klXLCkmemQ1d5m+1AnUsrwZGz6KM2xjv/WBAHn+Rn0rH5MOvNWEjT36z+LNKmNeejgajn7P1LtngNxZlpXUeSvQngNwTikRdP/zmp/g+KEuqmKr5bbcYb1J3K5F7Yx/X74QsRasmzbytK3NZbvmzIwyGIchdQfdBrt1VriKS0P/MS6h2SFc21gBYXYHaWROlrQ/26tDz63/IHI0BP/SUTvpdGV+V7gS5AQKO7yUW2eUg37ppQkAFW45HYBhqD0V0qK6hKbO4pG7LtNVlEbg3pY+GAzGo8Gs+YgHQTo3q4dcWWpqdSV0U2OtYH8xLt/tueRXh59SOzQMJKO8GnzIQgacOLLWZdsnymGEDA3s6DWpn5NxmaTFyvpXMGNsDGKFWAta2zpu+xtnYUCU61i44Cp86JFBwsDL+r1+QUqDtog/RmhbFA3cvg5QzdTeNSR0vzwkBwaSH0I+kO1kqSOX7MRImNNZ2mhDHmj/ZbqDqKp7XbojMLYvFKrXYk9xT2yrMpqK9sJsBmNNjBds3K8s0o=
