apiVersion: v2
name: envoy-proxy-bouncer
description: Envoy proxy bouncer with homelab-chart
version: 0.1.0
dependencies:
  - name: envoy-proxy-bouncer
    version: 0.6.0
    repository: oci://ghcr.io/kdwils/charts
    alias: homelab-envoy-proxy-bouncer
  - name: homelab-chart
    version: 0.1.30
    repository: oci://ghcr.io/kdwils/charts
    alias: homelab
