---
# Source: envoy-proxy-bouncer/charts/homelab-envoy-proxy-bouncer/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: homelab-envoy-proxy-bouncer
  labels:
    helm.sh/chart: homelab-envoy-proxy-bouncer-0.5.6
    app.kubernetes.io/name: homelab-envoy-proxy-bouncer
    app.kubernetes.io/instance: envoy-proxy-bouncer
    app.kubernetes.io/version: "v0.5.5"
    app.kubernetes.io/managed-by: Helm
---
# Source: envoy-proxy-bouncer/charts/homelab-envoy-proxy-bouncer/templates/configmap-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: homelab-envoy-proxy-bouncer-config
  labels:
    helm.sh/chart: homelab-envoy-proxy-bouncer-0.5.6
    app.kubernetes.io/name: homelab-envoy-proxy-bouncer
    app.kubernetes.io/instance: envoy-proxy-bouncer
    app.kubernetes.io/version: "v0.5.5"
    app.kubernetes.io/managed-by: Helm
data:
  config.yaml: |
    bouncer:
      apiKeySecretRef:
        key: apiKey
        name: envoy-bouncer
      enabled: true
      lapiURL: http://crowdsec-service:8080
      metrics: true
      metricsInterval: 10m
      tickerInterval: 10s
      tls:
        caPath: /app/tls/ca.crt
        certPath: /app/tls/tls.crt
        enabled: false
        insecureSkipVerify: false
        keyPath: /app/tls/tls.key
      tlsSecretRef:
        caKey: ca.crt
        certKey: tls.crt
        keyKey: tls.key
    captcha:
      callbackURL: https://bouncer.kyledev.co
      challengeDuration: 5m
      cookieDomain: .kyledev.co
      enabled: true
      provider: turnstile
      secretKeySecretRef:
        key: secretKey
        name: envoy-bouncer
      secureCookie: true
      sessionDuration: 3h
      signingKeySecretRef:
        key: signingKey
        name: envoy-bouncer
      siteKey: 0x4AAAAAAB1bbQbIpIhvAYwl
      timeout: 10s
    server:
      grpcPort: 8080
      httpPort: 8081
      logLevel: info
    templates:
      showDeniedPage: true
    trustedProxies:
    - 10.43.0.0/16
    - 10.42.0.0/16
    - 74.98.232.127
    waf:
      apiKeySecretRef:
        key: apiKey
        name: envoy-bouncer
      appSecURL: http://crowdsec-appsec-service:7422
      enabled: true
    webhook:
      bufferSize: 100
      subscriptions:
      - events:
        - request_blocked
        url: http://events.events.svc.cluster.local:8080/api/v1/events/envoy-bouncer/request_blocked
      timeout: 5s
---
# Source: envoy-proxy-bouncer/charts/homelab-envoy-proxy-bouncer/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: homelab-envoy-proxy-bouncer
  labels:
    helm.sh/chart: homelab-envoy-proxy-bouncer-0.5.6
    app.kubernetes.io/name: homelab-envoy-proxy-bouncer
    app.kubernetes.io/instance: envoy-proxy-bouncer
    app.kubernetes.io/version: "v0.5.5"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: 8081
      targetPort: http
      protocol: TCP
      name: http
    - port: 9090
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: homelab-envoy-proxy-bouncer
    app.kubernetes.io/instance: envoy-proxy-bouncer
---
# Source: envoy-proxy-bouncer/charts/homelab-envoy-proxy-bouncer/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homelab-envoy-proxy-bouncer
  labels:
    helm.sh/chart: homelab-envoy-proxy-bouncer-0.5.6
    app.kubernetes.io/name: homelab-envoy-proxy-bouncer
    app.kubernetes.io/instance: envoy-proxy-bouncer
    app.kubernetes.io/version: "v0.5.5"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: homelab-envoy-proxy-bouncer
      app.kubernetes.io/instance: envoy-proxy-bouncer
  template:
    metadata:
      labels:
        helm.sh/chart: homelab-envoy-proxy-bouncer-0.5.6
        app.kubernetes.io/name: homelab-envoy-proxy-bouncer
        app.kubernetes.io/instance: envoy-proxy-bouncer
        app.kubernetes.io/version: "v0.5.5"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: homelab-envoy-proxy-bouncer
      securityContext: {}
      containers:
        - name: homelab-envoy-proxy-bouncer
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          image: "ghcr.io/kdwils/envoy-proxy-bouncer:sha-0705407824f855bdfc620216c23b598edfc0563b"
          imagePullPolicy: IfNotPresent
          args: ["serve", "--config", "/app/config/config.yaml"]
          ports:
            - name: grpc
              containerPort: 8080
              protocol: TCP
            - name: http
              containerPort: 8081
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          livenessProbe:
            grpc:
              port: 8080
              service: liveness
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            grpc:
              port: 8080
              service: readiness
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          env:
            - name: ENVOY_BOUNCER_BOUNCER_APIKEY
              valueFrom:
                secretKeyRef:
                  name: "envoy-bouncer"
                  key: "apiKey"
            - name: ENVOY_BOUNCER_WAF_APIKEY
              valueFrom:
                secretKeyRef:
                  name: "envoy-bouncer"
                  key: "apiKey"
            - name: ENVOY_BOUNCER_CAPTCHA_SECRETKEY
              valueFrom:
                secretKeyRef:
                  name: "envoy-bouncer"
                  key: "secretKey"
            - name: ENVOY_BOUNCER_CAPTCHA_SIGNINGKEY
              valueFrom:
                secretKeyRef:
                  name: "envoy-bouncer"
                  key: "signingKey"
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: bouncer-config
              mountPath: /app/config
              readOnly: true
      volumes:
        - name: bouncer-config
          configMap:
            name: homelab-envoy-proxy-bouncer-config
---
# Source: envoy-proxy-bouncer/charts/homelab-envoy-proxy-bouncer/templates/httproute.yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: homelab-envoy-proxy-bouncer
  labels:
    helm.sh/chart: homelab-envoy-proxy-bouncer-0.5.6
    app.kubernetes.io/name: homelab-envoy-proxy-bouncer
    app.kubernetes.io/instance: envoy-proxy-bouncer
    app.kubernetes.io/version: "v0.5.5"
    app.kubernetes.io/managed-by: Helm
spec:
  parentRefs:
    - name: homelab
      namespace: envoy-gateway-system
  hostnames:
    - "bouncer.kyledev.co"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /captcha
      backendRefs:
        - name: homelab-envoy-proxy-bouncer
          port: 8081
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: homelab-envoy-proxy-bouncer
          port: 8080
---
# Source: envoy-proxy-bouncer/charts/homelab-envoy-proxy-bouncer/templates/referencegrant.yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: homelab-envoy-proxy-bouncer
spec:
  from:
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: argocd
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: blog
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: bluesky
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: mealie
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: media
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: pocketid
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: vaultwarden
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: envoy-gateway-system
  to:
    - group: ""
      kind: Service
      name: homelab-envoy-proxy-bouncer
---
# Source: envoy-proxy-bouncer/charts/homelab-envoy-proxy-bouncer/templates/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: homelab-envoy-proxy-bouncer
  labels:
    helm.sh/chart: homelab-envoy-proxy-bouncer-0.5.6
    app.kubernetes.io/name: homelab-envoy-proxy-bouncer
    app.kubernetes.io/instance: envoy-proxy-bouncer
    app.kubernetes.io/version: "v0.5.5"
    app.kubernetes.io/managed-by: Helm
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: homelab-envoy-proxy-bouncer
      app.kubernetes.io/instance: envoy-proxy-bouncer
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
---
# Source: envoy-proxy-bouncer/charts/homelab/templates/sealedsecret.yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: envoy-bouncer
  namespace: crowdsec
spec:
  encryptedData:
    apiKey: AgBGUUT7/2o8C+sSWLOq4mnQhTHRWSZTETFbmn/+JbFHguYly1aTSdCMgz1H9we5Hs2SBD+23TS7t3o6a8i5AqBylq8bfXCOAm6NB52dS6Thec+JbaUWCLQssOdz0g7l+w2+oz6iQJGhp7TYui2o7AO8tjnKbrckO2bcd0QhjQYAij+5MHUWYzo8i/yK+5ULP+dQ70+xvoWfhW30eDcL6uqm7pCRJ6y/M5ZcpL/5SrbB1SDP47YWhB9iEA5eexpEH+wzKz/Btj48lnzQOCoB0LhbPiteUHWjw3b7f47Bs418lrM2GWhbU40grLX4THvg8d5/7LOzJkR8BpM/k7htI9eMGPNstCgGRTASmAhCT2uKUS/nYfwoc4gXThiMBRz0cHeqrxnTbzqIOP1aw/a40bq+IjaVEHQmzvyz8i417gfoSnDRhmTjYQ0Yz80VxcMJepDSWSg/WufXGL7QkoKxJ+OW3U0tJVfJlSBuY4tgQ/Z0rOpCXAPvJ1caVczkkaq96kgXS1LOkYXZ5gTTJJQFWrgULaf5vPy42L0C27C1msoYdDZgyf0LYs/1Vw2x9MMBlDwyefgroEkC1yePQZ2brKJ78yf2jeJjlMcOa32sVo39NEZRqNWV7QiniJlXi/ZUcElV0gEaC25JUJbTZSTgKbhcxry7VjjsC4XZDTIDEiFVuykjWmx3mAt6+hh6D1MTbaYXg8pvQbYwhbtQ14OPpd8gvxaME4A+nDOmUOfaRgMQeaovcsbe09Xq5daU
    secretKey: AgBSJgWvlm1iypgzOq5UCOUrEjCrGLfOpFj9KU3VRoXMkROpjibP7MJpDm195CrSayWIS9XI5vJlRKsCfdB4UUhClmTMx87IDCRMuoYCvr1qX8IaaM2S5jGpBjPd+2Yr3IerMzEk8w9StC2HIh++QgQn3F+9aS+8RUVkUHiPULayGLRiWiO6R97plz1Pq+GeuiPM1X6flxTUGAVtVXTonsXG1ZhLQKucTJCsXHcB60Jtbq9AS58bGmmu/uv8Jgs+67p6STNOrxitsJluPRNAkdtBI0tJQ8zLGO2WeTB5O+pW3zhsaAGkxLOJjij3IPPkIiNFuqm3ImcIygl5XfEVlGC/ZG4N13qBYaHeIxExQ65SgVAzBitgJit4hXPfESAK6tAFDAVVRfK1Qa1n98OwuUEazp7BysPA7hg+6NcevH4PQFV3PHp7vS/sYiWflQrBODllTWeRLRp+KHJJAX5kumfDaLcOadbGSNMsTHejT4HWCtywL88YDKpplSrQfAcMMqcfuhOPt3uuERN9eON7WwMLME/015iF64gko1xnzPo/x9zi3yW810IFRGFCLDGexonuiwxMsWgs4Xoh8TSZQCudrd1SwWdmxe5ISJ+dkCQkz9rUBUifv8/eOZDybTJDm+LozXmzikMtCuhTb4li/hq0d49aG5o1mKGSEaIW1ZVuD/NhLH3LsBXV6CFBONKzb0EG21R1VpyvcGx+zDkPzws2aCytCUiEDHhZoRRFy8hstR7iVw==
    signingKey: AgBXOYMOmWRgNGg1ge/RWFJ881FYAKA8SutWC4iSsB1D/0i4R3kRHgw/HJf95x35ErRpn1woxc6/nt8y7BPgt0KcjggsGgECqyNzazvjjxxZskEI7vziGzb3gl76OYVjUG2pzzXRB1oUASscr2ssQk6/aeWq2N7NZgSrnnbL6bG2IaDkmXXfO4iBg8zb9QURIj4LnYCWkW/lCDYLnBwVQSe0VxQC5ifKM5AayKX4Fg+kV6DzOycJ2QEi8+TACrhth9Kx/1mMIxHfQOHBWCg1/gSxySw9d0C4TzUawh+iEuKTm+ixhgRiQAWEl0BV4mWHbe32+zZw0/1cJKvi8rVdJy4U5XYn9ZG62xIbJWttNX4yzWfavEUbJ56ChAlW6vT8uT1HC1uvhTSA6A9lRW7AQe+4+/MhcRQ0IXjlmLen5PJTbbbvNoAmIJjZ/wGbiQoKureiiGl+ZG39RRv4gE8UwQh19lTulSNzpCgm1o01xCHZZcxCABwClB/Dh+Z0QDTe5Xp29NQH8WoKiHQh2u4wVpGOnriM9W+2LIcnrY1I8Z2x8jl5GfSHAokScIcZ/k0B/qJL7QKRlDChUL3hkKeBVNatT2MU9m5wInSuoMeg9Uk5+Yv9+7phs207a3jiOzENnqrHpH0cildf+ZS9CFrMvFF/gfIQecrjPcRaS7azOr1fRKoQp+Fwty1V5w58E7IOzHS+TPZciHvBh5MJqJRhzJXY1DO1QvlAk5fIM00+AgGo4S1Bh8yVYEvueW1bTh71MBHA5QyBFJ9FWK2F1q3R5UCF
  template:
    type: Opaque
    metadata:
      name: envoy-bouncer
      namespace: crowdsec
