---
# Source: envoy-proxy-bouncer/charts/homelab-envoy-proxy-bouncer/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: homelab-envoy-proxy-bouncer
  labels:
    helm.sh/chart: homelab-envoy-proxy-bouncer-0.5.2
    app.kubernetes.io/name: homelab-envoy-proxy-bouncer
    app.kubernetes.io/instance: envoy-proxy-bouncer
    app.kubernetes.io/version: "v0.5.2"
    app.kubernetes.io/managed-by: Helm
---
# Source: envoy-proxy-bouncer/charts/homelab-envoy-proxy-bouncer/templates/configmap-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: homelab-envoy-proxy-bouncer-config
  labels:
    helm.sh/chart: homelab-envoy-proxy-bouncer-0.5.2
    app.kubernetes.io/name: homelab-envoy-proxy-bouncer
    app.kubernetes.io/instance: envoy-proxy-bouncer
    app.kubernetes.io/version: "v0.5.2"
    app.kubernetes.io/managed-by: Helm
data:
  config.yaml: |
    bouncer:
      enabled: true
      lapiURL: https://crowdsec-service.crowdsec.svc.cluster.local:8080
      metrics: true
      metricsInterval: 10m
      tickerInterval: 10s
      tls:
        caPath: /etc/ssl/crowdsec/ca.crt
        certPath: /etc/ssl/crowdsec/tls.crt
        keyPath: /etc/ssl/crowdsec/tls.key
    captcha:
      callbackURL: https://bouncer.kyledev.co
      challengeDuration: 5m
      cookieDomain: .kyledev.co
      enabled: true
      provider: turnstile
      secretKeySecretRef:
        key: secretKey
        name: envoy-bouncer
      secureCookie: true
      sessionDuration: 3h
      signingKeySecretRef:
        key: signingKey
        name: envoy-bouncer
      siteKey: 0x4AAAAAAB1bbQbIpIhvAYwl
      timeout: 10s
    server:
      grpcPort: 8080
      httpPort: 8081
      logLevel: info
    trustedProxies:
    - 10.43.0.0/16
    - 10.42.0.0/16
    waf:
      enabled: false
    webhook:
      bufferSize: 100
      subscriptions:
      - events:
        - request_blocked
        url: http://events.events.svc.cluster.local:8080/api/v1/events/envoy-bouncer/request_blocked
      timeout: 5s
---
# Source: envoy-proxy-bouncer/charts/homelab-envoy-proxy-bouncer/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: homelab-envoy-proxy-bouncer
  labels:
    helm.sh/chart: homelab-envoy-proxy-bouncer-0.5.2
    app.kubernetes.io/name: homelab-envoy-proxy-bouncer
    app.kubernetes.io/instance: envoy-proxy-bouncer
    app.kubernetes.io/version: "v0.5.2"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: 8081
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: homelab-envoy-proxy-bouncer
    app.kubernetes.io/instance: envoy-proxy-bouncer
---
# Source: envoy-proxy-bouncer/charts/homelab-envoy-proxy-bouncer/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homelab-envoy-proxy-bouncer
  labels:
    helm.sh/chart: homelab-envoy-proxy-bouncer-0.5.2
    app.kubernetes.io/name: homelab-envoy-proxy-bouncer
    app.kubernetes.io/instance: envoy-proxy-bouncer
    app.kubernetes.io/version: "v0.5.2"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: homelab-envoy-proxy-bouncer
      app.kubernetes.io/instance: envoy-proxy-bouncer
  template:
    metadata:
      labels:
        helm.sh/chart: homelab-envoy-proxy-bouncer-0.5.2
        app.kubernetes.io/name: homelab-envoy-proxy-bouncer
        app.kubernetes.io/instance: envoy-proxy-bouncer
        app.kubernetes.io/version: "v0.5.2"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: homelab-envoy-proxy-bouncer
      securityContext:
        {}
      containers:
        - name: homelab-envoy-proxy-bouncer
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - all
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          image: "ghcr.io/kdwils/envoy-proxy-bouncer:sha-dc5e8fa978ffc5814e8a553ce73489d42e80c8fc"
          imagePullPolicy: IfNotPresent
          args: ["serve", "--config", "/app/config/config.yaml"]
          ports:
            - name: grpc
              containerPort: 8080
              protocol: TCP
            - name: http
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            grpc:
              port: 8080
              service: liveness
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            grpc:
              port: 8080
              service: readiness
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          env:
            - name: ENVOY_BOUNCER_CAPTCHA_SECRETKEY
              valueFrom:
                secretKeyRef:
                  name: "envoy-bouncer"
                  key: "secretKey"
            - name: ENVOY_BOUNCER_CAPTCHA_SIGNINGKEY
              valueFrom:
                secretKeyRef:
                  name: "envoy-bouncer"
                  key: "signingKey"
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: bouncer-config
              mountPath: /app/config
              readOnly: true
      volumes:
        - name: bouncer-config
          configMap:
            name: homelab-envoy-proxy-bouncer-config
---
# Source: envoy-proxy-bouncer/charts/homelab-envoy-proxy-bouncer/templates/httproute.yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: homelab-envoy-proxy-bouncer
  labels:
    helm.sh/chart: homelab-envoy-proxy-bouncer-0.5.2
    app.kubernetes.io/name: homelab-envoy-proxy-bouncer
    app.kubernetes.io/instance: envoy-proxy-bouncer
    app.kubernetes.io/version: "v0.5.2"
    app.kubernetes.io/managed-by: Helm
spec:
  parentRefs:
    - name: homelab
      namespace: envoy-gateway-system
  hostnames:
    - "bouncer.kyledev.co"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /captcha
      backendRefs:
        - name: homelab-envoy-proxy-bouncer
          port: 8081
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: homelab-envoy-proxy-bouncer
          port: 8080
---
# Source: envoy-proxy-bouncer/charts/homelab-envoy-proxy-bouncer/templates/referencegrant.yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: homelab-envoy-proxy-bouncer
spec:
  from:
  - group: gateway.envoyproxy.io
    kind: SecurityPolicy
    namespace: argocd
  - group: gateway.envoyproxy.io
    kind: SecurityPolicy
    namespace: blog
  - group: gateway.envoyproxy.io
    kind: SecurityPolicy
    namespace: bluesky
  - group: gateway.envoyproxy.io
    kind: SecurityPolicy
    namespace: mealie
  - group: gateway.envoyproxy.io
    kind: SecurityPolicy
    namespace: media
  - group: gateway.envoyproxy.io
    kind: SecurityPolicy
    namespace: pocketid
  - group: gateway.envoyproxy.io
    kind: SecurityPolicy
    namespace: vaultwarden
  - group: gateway.envoyproxy.io
    kind: SecurityPolicy
    namespace: envoy-gateway-system
  to:
  - group: ""
    kind: Service
    name: homelab-envoy-proxy-bouncer
---
# Source: envoy-proxy-bouncer/charts/homelab/templates/sealedsecret.yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: envoy-bouncer
  namespace: crowdsec
spec:
  encryptedData:
    apiKey: AgAmpbldnxUnUddFtmZYThncAS/f4dP2iGSeTBTum8Ojs83gcFw7Kma0moD0o79bX4R03ZlFoRBGTBzZhZpuWrgNc+MVbaRK8vRwfnUQhUhhbb9IoyrIYppbdygyaFl78/STAh/W4km1bjMkgJJsrR/w2C8oBWH69VjyHQ1Q8xyAz2GriQgNxrIGMby1MldXmbIwROanwUsM1jjXMXcc0mXYFWe5HEfFU6Rfqhl1234J4MO3mV1UX7kKHmdi8jJpuGv3cZ9pZiTWGiB/Sbj57auzRBigs3j5DnOS3L669BdIsbBmEVGOCZVZS/CK4uXjOaulp+Jz1jQEQ+xHVZ7ps6QzeXXohyZZXKGfc/SWx52vZqRgeQazzZTnY5HLeQ21aqK0MiyeGYaWo78Z1W9ibR/ifreQFN+UrGE/u1mBcyJFTi5A00kGjwXSKsg5bcCRChLmeYfIEsf9wxBr7u5dZ+D4npFpQQRUd7b1R9snVCR3FsLqT+7Pted1cliU6UCx40L1QS0bV9U3hCRRKb82LBPOI8YQOvbvursIJFY6aKUG/TqOCELfhMMvA9BV2xG3exrJY4g5EDf+6YAMYQVYrYLJMLGUcBx2ihdgxYVaTHmFpcBcDosetyqpRTV3dpiX9M/V3UOM/jop72Xdt3ZkxJWLnlO9xWyXDDbkz3r6/R64pvOg5DNyZX3tXT2oxitWWvXGzuYG/SynrxMlzSLWl6HYH8yb4CECwY8ipAmjDjCqTHjA6UKb2X5kQojN
    secretKey: AgBY5r3mGml1Q0T+xDAGHLvEIHkP8jriaqLckNjUpcCQpJn6VAw2zx3svOpYtx2dvotR32n55DGsdTMwNYkaOFY5PFNxb6qO3pD6lXuWZBlGh+VKuS6/1sfO6rs76R/daPq+YmBvSLHvgsVXvMggpR8pZtFeyKzLtBr+qQ5c70rvs3IZ+9PZ2nl2F2QxjKEOBDr2zpWqmL7crrUnXFF/fDhNVbPDlZzdnanUQuViOW32e1aY7jYCF4HuW2dZAPELQRGAD+bcXRPvgI58dJCz+42dIbpzHGWVonsiSVn1YOTKeQsbUZ+Gt+Qhtk2omonUw6r3Rj7Oh+oK9v+wfN0VOIZ+DRiewXm34tQ7bHJKKvImKP1N48Z7CPzTOdwl9UBje8b7nz75WkRisW0IhSV/BBggQpDU0GPXLkE1qEmtvXsMuZVffFfqLFrtmCODl3dTwfQCJzoAglqSE7wbvU49W9VH1hOIG171Vs/2eCWDfOnxHpp1zfgxdUPaYGh+OpY2RYcZzi2P8/EhWLteY5IQgJCjja+skRmTwSQV8IobGZRlF11BZiTRMbJXXoVvVLvPQfOsRP0G5pwQaqwJc4UAe51bWGBcC4LMrW/s7cqFLkmhIt1j6fxGfaZwYiXL3ac80mxjqtF3cMSjqZOr1OgIwfCwuUq0+uDseJcbyaUfa4OsJj935KODnuEWS8gooeFVufCEU7cYVho0SWaP7+n4zummqhDX5fK4/18Jbw4fYtCjzS0zeg==
    signingKey: AgCOxZjLkqCNDp2+6jT8XozGGZ67P2Qnd0pmu7wHB1Br5hH+Tp8Nc8GqTmgZ+XkTmfSg4OAPPYyGtued0Rd3hnKP9ebHScDrglMOZwWeSBAc10xKB2Ss4ueNrsGQlgAW81yzv6r082JbPM8BS+IXqdbolfDAGixhn/TbzB1ZKLZgX2xmj/zS3RpKo8MK+AT9Wblh0ATSX4jymSiSZ/H90EK8F8s6qCyQsy8IeuFAlu5gT3XhyvgleZukmOVSh7H/GkxqSHdmkVUiW5peyx3JA/gXEWBCMarsZhCuKPGgL88JacfsRd+tC2QdhoMfAphNBMijJSJJT3NBh2GBKxQg/sMYG6iQdycczDeowPLpXEksXA6xLLmTQExc3/dIaU7uSBjFhTNNfzPx5vypYqB5xgRJIbh/Yav/MJX8blgFf2ltMFFdeboqkkzLzBiJXqBz9owXZnXnjbYPqdJlBD6d7W/rcOfgWNLPNSHFkWIuCI0bG0NELILIU4kk00iPuovc8AklBZMwXy8o662y0l8ADkjCmmB3cikjZIPg0oe2ls1ASA/41KkaoTU+/COLy80cjv+ihUT6GAUAr3ce7FVzsVO5rRe65WW64gtLTPo3DJe6Oi3lfgc7Mt7ydHW7C534yqjMVij8N17YPLVXuTBsn/f3bY6PF3rPjU3PTaNAr4QznV4Fg5sPLktGPMM3NCZk5a8C5VZPxcemn1Ez1IrRiqmmzDcl/CKirmRjaYSgjamA+aYkDxX15O1WFJRuoGGCpKYU1CYx8HSnst4yS0KbFLnW
  template:
    type: Opaque
    metadata:
      name: envoy-bouncer
      namespace: crowdsec
