---
# Source: envoy-proxy-bouncer/charts/envoy-proxy-bouncer/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: envoy-proxy-bouncer
  labels:
    helm.sh/chart: envoy-proxy-bouncer-0.5.6
    app.kubernetes.io/name: envoy-proxy-bouncer
    app.kubernetes.io/instance: envoy-proxy-bouncer
    app.kubernetes.io/version: "v0.5.5"
    app.kubernetes.io/managed-by: Helm
---
# Source: envoy-proxy-bouncer/charts/envoy-proxy-bouncer/templates/configmap-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-proxy-bouncer-config
  labels:
    helm.sh/chart: envoy-proxy-bouncer-0.5.6
    app.kubernetes.io/name: envoy-proxy-bouncer
    app.kubernetes.io/instance: envoy-proxy-bouncer
    app.kubernetes.io/version: "v0.5.5"
    app.kubernetes.io/managed-by: Helm
data:
  config.yaml: |
    bouncer:
      enabled: true
      metrics: false
      metricsInterval: 10m
      tickerInterval: 10s
      tls:
        caPath: /app/tls/ca.crt
        certPath: /app/tls/tls.crt
        enabled: false
        insecureSkipVerify: false
        keyPath: /app/tls/tls.key
      tlsSecretRef:
        caKey: ca.crt
        certKey: tls.crt
        keyKey: tls.key
    captcha:
      challengeDuration: 5m
      enabled: false
      secureCookie: true
      sessionDuration: 15m
      timeout: 10s
    server:
      grpcPort: 8080
      httpPort: 8081
      logLevel: info
    trustedProxies: []
    waf:
      enabled: false
    webhook:
      bufferSize: 100
      subscriptions: []
      timeout: 5s
---
# Source: envoy-proxy-bouncer/charts/envoy-proxy-bouncer/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: envoy-proxy-bouncer
  labels:
    helm.sh/chart: envoy-proxy-bouncer-0.5.6
    app.kubernetes.io/name: envoy-proxy-bouncer
    app.kubernetes.io/instance: envoy-proxy-bouncer
    app.kubernetes.io/version: "v0.5.5"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app.kubernetes.io/name: envoy-proxy-bouncer
    app.kubernetes.io/instance: envoy-proxy-bouncer
---
# Source: envoy-proxy-bouncer/charts/envoy-proxy-bouncer/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-proxy-bouncer
  labels:
    helm.sh/chart: envoy-proxy-bouncer-0.5.6
    app.kubernetes.io/name: envoy-proxy-bouncer
    app.kubernetes.io/instance: envoy-proxy-bouncer
    app.kubernetes.io/version: "v0.5.5"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: envoy-proxy-bouncer
      app.kubernetes.io/instance: envoy-proxy-bouncer
  template:
    metadata:
      labels:
        helm.sh/chart: envoy-proxy-bouncer-0.5.6
        app.kubernetes.io/name: envoy-proxy-bouncer
        app.kubernetes.io/instance: envoy-proxy-bouncer
        app.kubernetes.io/version: "v0.5.5"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: envoy-proxy-bouncer
      securityContext:
        {}
      containers:
        - name: envoy-proxy-bouncer
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - all
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          image: "ghcr.io/kdwils/envoy-proxy-bouncer:v0.5.5"
          imagePullPolicy: IfNotPresent
          args: ["serve", "--config", "/app/config/config.yaml"]
          ports:
            - name: grpc
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            grpc:
              port: 8080
              service: liveness
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            grpc:
              port: 8080
              service: readiness
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          env:
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: bouncer-config
              mountPath: /app/config
              readOnly: true
      volumes:
        - name: bouncer-config
          configMap:
            name: envoy-proxy-bouncer-config
---
# Source: envoy-proxy-bouncer/charts/homelab/templates/sealedsecret.yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: envoy-bouncer
  namespace: crowdsec
spec:
  encryptedData:
    apiKey: AgCTi3o4KBXZCY7Mmo7R33qfsXzm8r/O4T62uDoJhz6URgt05P0imtqG2VLggFnG1O3cYsCxEh+fhmDBuvFgI5UivwNmpub7wCrjRLWgOJqu5C/vl1BqUToyzx9EGY/493vde2PezhNknDgkc7Og8nvgZzjMFv9rKoqSU+syMsL5ztJEUGDW8o2GJYUQhBvLfc3aecBIPyRdBhkjVE2R2+hq62GUW/cDY2LwWoqCld3Hrj5k0J1FidMzMhAMYckxAHnwA9zUpdgxnMMD/nfuQLGphVFca+xCCL/f7plZ71tR/oNpd4e4eN6oQQVjs+gd0qFPVPIKb2FHho+J4i2I3WIbNqnH/9HvN7IAMb1HYkf72LpOe8lMiN5qWnrVGrE3uJ0gBegWi/jUI5p9LyYDZWAOdoH7+B1bHdrxy84KPdgYMlTd8AFHcyZHpNjQM6R3KPVH1qIASlaB+voRJrCuKPpz4bj/U16ND3teSeqkgA/RlHf5f9mbNGmDf9hhRT25xjOkVtcguemdTpMqT3hIUm0KjKUhpALe11Hw9Y93i5QNLcgUgUPp9a3y81LRaQfMUa2PLQvwAiwm0jFSCbQ26fEl/Pk1enyoa1TD1LAnj5HWhRof6jOrnq+dM3jm+1ZRBp5BZ4zbRQ+NG4LbJ3jmDxMkVl8WUIaqfptdh2M+LySJlDNogIX2OrPqOZz3g7j5TdcS2b3/NbFGVrpyA5gL+MxXps03XFhnDB8PmKkn6kqWYlrtKzBoGAts5mbx
    secretKey: AgBASAITbBGkl8QTNGNlycUpIpML2PdLCDfVvB2ipaACkhllajF8TRfIeGTm4V6UpIqSXeUaHA7rwWRhwJoflLZBBy6mC9Xohl8Vi7I4k7n+uhbmvKJHGFKcL72ne4EZxKFuZmGl8VQydnx5yVx+i0e2FynAmPKrCG6lGdE5W8+Q7kvt9u4M3QaITq7y4Hbb4nOvn2U7g1dP7YUvHkugbAO2o62MFFPLWCXrulgZM3e05nRvlVko16adxsyv1iu9RnTbAI294Z+st54ygq0QVOBUegZU9wrzSPl2OYxdEnoMBeVix6tkzvjg92fn9AMRvJPVh/emdPvgEXfDG/A75dlezdk20oUfwQPvr1PggJaf6VRT11UVJ6//89akoQ9SmiVsO4TtpLx869kHt+Qmf7nhFU0QeviEN9CBGiUubQn5qVu/axyeWPI34NMJOi17UlJZFPufZlACC6SfyCsDWT3iW/9lp9+OFRU8XqDdl6x/G2OiFpGsIjhKV9bLv4Eu0qUn3Hx5oF5XDS/Asd/JPa4UNzlZHsOo5EgV/7ZiZah+GH8ER9AW6ZeTGPlp5D2VMUUlxySOYbck/xmfSxKBot00FXsLvBSb7rj14XlIy6vsYcybF059a7VQlHmZGw055MzKAngfxY1b8dGaZBMtixyozyVAtrJdOhkXnv5VSE5iy9bSHJwIGLnsZjZ3vANGW5Qsa9rDynfjwBWr/tMx53q+y88k5CF4nv6zvDOqzlwck1+S+w==
    signingKey: AgCQfonucPWTiLSaBZE/GgGikZHcRWMTHq9zCFENZ8W6enlY0C0esvT/JdmYUsaMFvsrQb0DEkcGLG1TPkjmr2hGtq+aJVUi5nztvDTFlVqPjiJrKAfe0rFCAVyqAseT5QzeJ1kprnzI3XEzOfOILMZYFlPMVolXO4bCiXoxFeYmgAJLwsUL4hSLgwcXATCY0b8k8chNoA6CJ+Kc7s8Llns6eFhlhGR2QpM80u0+pUDaXlXovHfqNZNw1reAiE9VMP9Zo0/hbgNIhVGBayZizkHnrip/xDDcTWIZpYSl5TEkz+jObPGqE9dWH7rVeLjzs25AMFoZga6cC5752MGId3yh0NhiBMXVZYqRUTFsO9hAkl4bIc7gxr2UxbY6qGZ0ho3MxOx7EnWx/y2sIoqoC/LhEXZXEUvY74ZMR35XsYVg4ij8+Lrh/QCTxO8lSWIVy4Iw8yoDWvjb8bMC8n+6U6kevuIFyK+0ElbIpZK3MOn9yVor9VgNJrcNeYULYqd/ejKDqCeeMsk1FgcP9Kp1mRtUf5HpojIG1bOPEnL16sRMzZ8svUbc8g7m2qAib4Us4KtnvUJs8zXXxLQmLR94sXDsxvRwFCmEQb8J//nnLzxc2aAA5k2U+9iFNrzV73I9pwcwqFbFxPdVu7Bb2JLG7bcX04Sn13fdk8lAaPD2nNnL+DyOz9D+1qSEV8hZLfGdxPRS0aOXLI9iz/NPjASTLiUvULhVRaQtFVqLsHRwOxGI5xu4aBKWdIsfhq+xuL+YuskEEIo++VBltlaWm0IftWes
  template:
    type: Opaque
    metadata:
      name: envoy-bouncer
      namespace: crowdsec
