apiVersion: v2
name: coder
description: Coder remote development platform
version: 0.1.0
dependencies:
  - name: coder
    version: 2.33.0-rc.0
    repository: https://helm.coder.com/v2
    alias: coder
  - name: homelab-chart
    version: 0.1.22
    repository: oci://ghcr.io/kdwils/charts
    alias: homelab
