apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: cnpg
  annotations:
    kargo.akuity.io/keep-namespace: "true"
---
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: cnpg
  namespace: cnpg
spec:
  promotionPolicies:
    - stageSelector:
        name: main
      autoPromotionEnabled: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: cnpg
  namespace: cnpg
spec:
  interval: "1h0m0s"
  subscriptions:
    - chart:
        repoURL: oci://ghcr.io/cloudnative-pg/charts/cloudnative-pg
    - git:
        repoURL: https://github.com/kdwils/homelab.git
        branch: main
        includePaths:
          - glob:infra/cnpg/environments/**
          - glob:charts/cnpg/**
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: main
  namespace: cnpg
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: cnpg
      sources:
        direct: true
  promotionTemplate:
    spec:
      vars:
        - name: warehouse
          value: cnpg
      steps:
        - task:
            name: git-ops-clone
            kind: ClusterPromotionTask
        - task:
            name: helm-update-single-oci-chart
            kind: ClusterPromotionTask
          vars:
            - name: chartPath
              value: charts/cnpg
            - name: chartRepo
              value: oci://ghcr.io/cloudnative-pg/charts
            - name: chartName
              value: cloudnative-pg
        - task:
            name: git-ops-commit-pr
            kind: ClusterPromotionTask
          vars:
            - name: commitMessage
              value: "Update cloudnative-pg chart"
