apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: vaultwarden
  annotations:
    kargo.akuity.io/keep-namespace: "true"
---
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  promotionPolicies:
    - stageSelector:
        name: main
      autoPromotionEnabled: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  interval: "1h0m0s"
  subscriptions:
    - image:
        repoURL: vaultwarden/server
        semverConstraint: ^1.0.0
        strictSemvers: false
    - chart:
        repoURL: oci://ghcr.io/kdwils/charts/homelab-chart
    - git:
        repoURL: https://github.com/kdwils/homelab.git
        branch: main
        includePaths:
          - glob:apps/vaultwarden/environments/**
          - glob:charts/homelab/**
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: main
  namespace: vaultwarden
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: vaultwarden
      sources:
        direct: true
  promotionTemplate:
    spec:
      vars:
        - name: targetBranch
          value: main
        - name: warehouse
          value: vaultwarden
        - name: imageRepo
          value: vaultwarden/server
        - name: valuesFilePath
          value: apps/vaultwarden/environments/homelab/homelab.yaml
        - name: imageTagYamlPath
          value: vaultwarden.deployment.image.tag
      steps:
        - task:
            name: update-source-main
            kind: ClusterPromotionTask
