apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: vpa
  annotations:
    kargo.akuity.io/keep-namespace: "true"
---
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: vpa
  namespace: vpa
spec:
  promotionPolicies:
    - stageSelector:
        name: main
      autoPromotionEnabled: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: vpa
  namespace: vpa
spec:
  interval: "1h0m0s"
  subscriptions:
    - chart:
        repoURL: https://kubernetes.github.io/autoscaler
        name: vertical-pod-autoscaler
    - git:
        repoURL: https://github.com/kdwils/homelab.git
        branch: main
        includePaths:
          - glob:monitoring/vpa/environments/**
          - glob:charts/vpa/**
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: main
  namespace: vpa
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: vpa
      sources:
        direct: true
  promotionTemplate:
    spec:
      vars:
        - name: gitRepo
          value: https://github.com/kdwils/homelab
        - name: targetBranch
          value: main
        - name: warehouse
          value: vpa
      steps:
        - task:
            name: git-ops-clone
            kind: ClusterPromotionTask
        - task:
            name: helm-update-single-chart
            kind: ClusterPromotionTask
          vars:
            - name: chartPath
              value: charts/vpa
            - name: chartRepo
              value: https://kubernetes.github.io/autoscaler
            - name: chartName
              value: vertical-pod-autoscaler
        - task:
            name: git-ops-commit-pr
            kind: ClusterPromotionTask
          vars:
            - name: commitMessage
              value: |
                Update vpa chart dependencies
            - name: prTitle
              value: "Update vpa chart dependencies"
            - name: prDescription
              value: Update vpa chart dependencies
