longhorn:
  persistence:
    defaultClass: true
    defaultClassReplicaCount: 1
  defaultSettings:
    defaultReplicaCount: 1
    taintToleration: "node-role.kubernetes.io/control-plane=:NoSchedule"
  longhornManager:
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
  longhornDriver:
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
  longhornUI:
    replicas: 1

homelab:
  httproute:
    create: true
    hostnames:
      - "longhorn.int.kyledev.co"
      - "longhorn.ts.kyledev.co"
    parentRefs:
      - name: homelab
        namespace: envoy-gateway-system
    rules:
      - backendRefs:
          - name: longhorn-frontend
            port: 80
