kube-prometheus-stack:
  crds:
    enabled: true

  alertmanager:
    enabled: false

  grafana:
    enabled: true

    admin:
      existingSecret: grafana-admin-secret
      userKey: admin-user
      passwordKey: admin-password

    ingress:
      enabled: false

    persistence:
      enabled: true
      storageClassName: ""
      accessModes:
        - ReadWriteOnce
      size: 10Gi

    service:
      type: ClusterIP
      port: 80

    envFromSecret: grafana-oidc-secret

    grafana.ini:
      server:
        root_url: https://grafana.int.kyledev.co
      auth.generic_oauth:
        enabled: true
        name: PocketID
        allow_sign_up: true
        client_id: $__env{client_id}
        client_secret: $__env{client_secret}
        scopes: openid profile email groups
        auth_url: https://pocketid.kyledev.co/authorize
        token_url: https://pocketid.kyledev.co/api/oidc/token
        api_url: https://pocketid.kyledev.co/api/oidc/userinfo
        role_attribute_path: contains(groups[*], 'admins') && 'Admin' || 'Viewer'
        use_pkce: true

    sidecar:
      datasources:
        enabled: true
      dashboards:
        enabled: true

  prometheus:
    ingress:
      enabled: false

    service:
      type: ClusterIP
      port: 9090

    prometheusSpec:
      retention: 3d
      enableFeatures:
        - scrapeconfig

      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: "longhorn"
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi

  prometheusOperator:
    enabled: true

  kube-state-metrics:
    enabled: true

  prometheus-node-exporter:
    enabled: true

homelab:
  sealedsecrets:
    - name: grafana-admin-secret
      data:
        admin-user: AgArJZ7o3w5F1vNCxp7JGe7NeJnsnSJRaYYCq+Kk5U8YrpPOrwb91sCBEGxDzQWCXnMHTK9OLAO/Cnm9q9tg+ZkoFrZXTF8YgRmhquWVyxdTrVDbz6hWoXm2U0/vpqJW+yrbTuR7rBEaqJv7u+RVyy+wfXrXZ6aP53vQ93Fc3D8ZFmSYOyYfvBDe7e6Yia4gKjLSPs5d7KiZsLFsjp5KmavL0glKjJIs2tu30/Tutv7KqN6gvwxbRJsVRMQHf5z+yI4eYvrN1NfLTY+XOxILg/fwO15zkw/w4QXeh+0fRFjcbrKMaB8X8+JnBRvswKFfeiVoP6029KDlJxde2Y65tqLyAo0HxIAz9EPbwnFIedTL4RpGxpn6D/LvM29JwuHpnB6IdTPUH7N7mmD4EisRo651lxBMq8e6OXKWL49gzhbnCwsC7e0bxPJU4IAxkQOfJdtSCtdlHRVy+8sewU+ROujdVuHNUN/SvTBLMZV4E+1D1jP7uyqjC4tyhxFv9XDOHZYL9ZUtp+LnizpejF82Ix7B3oQveSenpkWu+4gvAk07lFXaoD9N1xLonqmdldQPOZ1NNqNHiFUzU8y9yI/q/4oXPFaSu4k8V6ArVFq+dcYLSWY8vSqhq/iOauz8DD5GFnGftxN4iw16iau/QHo943IwmNByIwo5gn8ufkkewxLNXvoORu1fP0emh4QnPBbSeDSfWYc6ig==
        admin-password: AgBXyITD4EmMOLmM9YEodkNoZOWyJ2+4NWp7t24lQeZ5He7H6mF3bscenVYxqkshzRHHM4NPmEEzs6xWsJ247CXC/fCrJ/WvRmyNzAGo4HEirzk4dpX+95bKUigY82zOaXLc8MUzLO5RbGGkYzFmgpZFnXmX/Kf8LPPXvWtL1VrRymf+dHctQ/uragrC57yjAp3y30Gs8lUbENhdaeSvSDtrfSLKkRBOrEia9o5X+MEUBqN0fhr7S2VJMaU1WE5viBrhSdHYOpUeI5jrz36pe9mGdgIKxN0muCcSqxAPBPV2eDUUnMRFnUtTM4Y1KzyfgHXka7GcjbwcJTay05YtSwfuOjG1ONGxg7BTmms/LfWLkU8DfGgJ6cWlAN7xyRywHkefDNT2N1CQgiX1vlpfUaeUN1AwtEGONcAOUIhXiop6yjZBQ79KBBZ8lpfJ47Yl1t8Q7PB5/zaPiBnOD5OMae2kHC6uQVpjyY6tsLce6TZ51nMcATgRb8qNFAyvTgZ62wihRvD4T7frh3gImg5eWIoHzUchd4L26j9uqd07yqCL/NBwWzS8pmvLF8amt4patgemLn0Q/MlEikDWyB9kFc+pXeQ42ocrgdsNKveaZMJploCeq2HyleDAk9CZAhLzGJ5XZ2czafTiBTeGqZWiLHB2R9O4Jyk05HAIhFQdWLXm1rLSKFN4LyRK3jbJw/zn+k4iW2Xe2w==
    - name: grafana-oidc-secret
      data:
        client_id: AgAxRU9gA1OkG8R7cfutfragtCmHJ4S7OmkvSpbMDvvhp+3zhBzF/PUWe0Icoa5JxblUpm/O57lShVPUQBlIZXYkrrHd0QjyW7zP9S3REUDhRsWUwvCHiPo7mjeuLIlgCwlwQjm+a896HnFxowIprhr1bHIOZofJbX8CWhO5SnahxRLr879LRc6jUQPALMyZtzeg6iQlZ7dzVtQYpemEurvT0CxwlCf7YNJdTjAgdjk5360fh5UaJzKxm7L+/CPm7MXGZqnCN/7yLxAIxxEg7VLCcve0b0K34NR85pEOnN5XPZIPA+RDGA2AqSVkTIuXB9kvYwkLYyHBx4+4d3si3DWpSrm25WDZ4ReUFS0FYUV/WCTgF86E6JOmXLubwGItgkLqpaqBhYbQR7eZv0e+kpMqdMwoUXVjKQFADlAjcDAbW/uUbW2o/pS7O27+vQnxHDftJojiPG0D/5MhDs3whNDnw46XNSo2dLmSRP7rfKlYxei5ypV6ax4zZ2FxfB5/41420R8rf/qVsBcHOe3uRXPj98610fVpzkcR74s9rHWD3pkL8dYH8xesyT9kYp00sDnBV+Q3dhnXU8hGFh+my0a8EdtTXZXDw1oU0Py1G5ogXtU16Sn5QnAc9n4CbwCfK77zy5gZobVNHwqLZcOhgvQ5LbI/wUorX/GLDBJ3UfmB13DteQAqjMKlRCU676/4q0iUTVq/eQjuKTuDGPv4OD/+DSd7yP1+xo6GIZYnfPT6xWZZfR8=
        client_secret: AgC3gzI6P66kqM3k7Xm/DgvRoKdPfyQ6Lt+KV+5KKWyh+s+4cxTXcK1Dc9ug8k2/OTgFPszObH1mzPLFfO1oFEJ4A6In3KkSHQtv00mh78gTL5RDrxbULLPR1a0egZSEJYkbsw/laot2E1Ua6zyiZErZLe3K2DKOr4dJG4IhmNOaKt233K6+oPNtZOwvlTU93/eN/RBicMWnELuJ0vnDHhKtKpLTzfTO5pbjE46ijCkyKMHVz059B6uzo2PB+81ugT5b3iiV4SJuGC21s4yme4PNdxA4tkREADkNCAibiScci4dbYOm9muLtBGB8WEyfBGpDIrKXqQGyukScGB1e6AXZ01zUbmuufO6qI3erJpaNoy6kR6fR/Xk2JoxTCcylHpiYuU6EPXzZA4qAhphQ3/5QClxFwXqjg785jI7VBerRsHTnkcq11A1LV7VSVgrMOzm04gAKhUbicpGc3uCYe7Rv1cTk4rXIC9LxsQmL+5CsoaVxZz6uzdeOUFszEwbicCP4K+KI5rgYdt2EkyOC674e9qrPoZrqxuuh0h9zgom8r91nwOF6gH0+swG3rASMCPDO04Z+05m2MSqrRzBLsel5kJa+saMf1Fz6Vb/xZfcnHbndmvmnyzLxfIslcnuJUSbba62j98OlDvAgznnmNdbsTfJB37/1TK2qbUb5cT7l9H1VN/Oh7foSM5+vFAxGclRJgG8dhLHlY2pTXP0lPJWg85UlcmnmPJMgpquaG+81KQ==

  httproutes:
    - name: grafana
      hostnames:
        - grafana.int.kyledev.co
      parentRefs:
        - name: homelab
          namespace: envoy-gateway-system
      rules:
        - backendRefs:
            - group: ""
              kind: Service
              name: kube-prometheus-stack-grafana
              port: 80
    - name: prometheus
      hostnames:
        - prometheus.int.kyledev.co
      parentRefs:
        - name: homelab
          namespace: envoy-gateway-system
      rules:
        - backendRefs:
            - group: ""
              kind: Service
              name: kube-prometheus-stack-prometheus
              port: 9090
