kube-prometheus-stack:
  crds:
    enabled: true

  alertmanager:
    ingress:
      enabled: false
    
    alertmanagerSpec:
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: ""
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 2Gi

  grafana:
    enabled: true

    admin:
      existingSecret: grafana-admin-secret
      userKey: admin-user
      passwordKey: admin-password

    ingress:
      enabled: false

    persistence:
      enabled: true
      storageClassName: ""
      accessModes:
        - ReadWriteOnce
      size: 5Gi

    service:
      type: ClusterIP
      port: 80

    envFromSecret: grafana-oidc-secret

    grafana.ini:
      server:
        root_url: https://grafana.int.kyledev.co
      auth.generic_oauth:
        enabled: true
        name: PocketID
        allow_sign_up: false
        client_id: $__env{client_id}
        client_secret: $__env{client_secret}
        scopes: openid profile email groups
        auth_url: https://pocketid.kyledev.co/authorize
        token_url: https://pocketid.kyledev.co/api/oidc/token
        api_url: https://pocketid.kyledev.co/api/oidc/userinfo
        role_attribute_path: contains(groups[*], 'admins') && 'Admin' || 'Viewer'
        use_pkce: true

    sidecar:
      datasources:
        enabled: true
      dashboards:
        enabled: true

  prometheus:
    ingress:
      enabled: false

    service:
      type: ClusterIP
      port: 9090

    prometheusSpec:
      retention: 30d

      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: ""
            accessModes:
              - ReadWriteMany
            resources:
              requests:
                storage: 20Gi

  prometheusOperator:
    enabled: true

  kube-state-metrics:
    enabled: true

  prometheus-node-exporter:
    enabled: true

homelab:
  sealedsecrets:
    - name: grafana-admin-secret
      data:
        admin-user: AgBFvtdmn3Ot7pAaCyx21vGfR3gnW2/S3sZTHzbwQUr6NZiVgVAVTqr29w7+31WeMb6fbAG9mE2CSIW9YfLwMhPeJ1km4h7Ml/n4LxnDC1A8J3LI6uV/tVo+ipZNXFlCOybuUhGEfEibsValAJl6sR2juUdj3MXzupK96XHm/DNxEN67FM3iBpgg3Mo6gRjTetL8iBmNk8Z7+YPkheANgYA9LeajC6WKrzcbkEJAjvld0gXDXk8K1zudOaAUX2xWemckLUkRagmI4icboGRFk3//yZfKoDAf1dWePyjOBO40c+WBQAnZEhRo44MJ2Y08sSoCKpVT50QsKUr1/kYqx4WbWUqI/rP8saydelwW1O2wP5PBNeTCOCoVTNCGVnGKDrxugR6XaVSyQuIBZKgkjbsjmL5XXlO7s3+JetwQBdMPObaxbnLQRjFe/adoVvgsdQBCjA16IlKn+cYWEebn9iUWxA3Jzg+8HP4ensjQne4vx6un50xlBLeW4brGt2xzQW/mjdOIl616Bnlm8GDGwnMjNzHbWUIlM9Khnz3GoWa6YXe4A8dtRlKsFmS9DVVJcJMlzgqfFS+RX43uzaQlG53dhQ2a5Mpl8owmxlWrcfGKTfwwsVzV3HLnFGpELrDn1s3a9EM53+cO3ZG3DsfzPPAdLmxfc7YXk39pvpH3l3uim5a3WJs+5mOCPJXAIWoPupZElbG9uw==
        admin-password: AgANBU3VLHNpgMrxXvMT1RXrMuT5V3T7gD2JRIXy7c4ychhZWYqVpifI8kDNaqUFZzqUpyYLiQeDpHoS7ixUZq9/lydkQsIkGlF59GCvcWi7VBm2nvMq8OEzQqPYooHaAmI7w3kW7iJUOYCa/3RPu2qC/e8StB6DUDjE9/HsvTBeaWVdM9QWmvVX0ZzauRmQ5aufU6929/9zMryyg80Mc+A0vd8VQqRCyWssQ5S4oOGGoK7WK1ZTX1dcxzfPKCAZWxDVcek08WRYR4V0rv4zAuFhSP0E57oeZf5ApVvtaVAUmxWdaOSTyxgQWJ0pBM58TtKwvloTmXN65jFqKvW+TmW4hqJ4Rn8fyx/W/kQ+NqJpy9/DWtHNbqMMeS20qkHvoRW3YCctqeTbECRNT1JM8xXOEQ6xaozF9j4bZW5efoK7yYFqycn2YxPsFAtbsLEzadkcgWa3xwPmC3e1vWbjFcfL/tNHBTye+WOm7oeQc+8PSKMNWUPZ4TufS3JzrXEyQf3u/6tc+7koEIrKZZugipfo5PjcuadTxZBH0cidmanOEaHuD0aE9ij3UKBuWnqmYI2fjRsPieQ8SKd1s7x/14BqC7t0gG15fcjEZU+6/PQ/LnrKrRKDkNTSMxprVr/DAVUUHzE7XAlB4LWaQnmKB7jSeF8GkEjkQlWyWf3Oxp6BbW6vDDtTF3g9+YrDshXADAqqUPcVyg==
    - name: grafana-oidc-secret
      data:
        client_id: AgAxRU9gA1OkG8R7cfutfragtCmHJ4S7OmkvSpbMDvvhp+3zhBzF/PUWe0Icoa5JxblUpm/O57lShVPUQBlIZXYkrrHd0QjyW7zP9S3REUDhRsWUwvCHiPo7mjeuLIlgCwlwQjm+a896HnFxowIprhr1bHIOZofJbX8CWhO5SnahxRLr879LRc6jUQPALMyZtzeg6iQlZ7dzVtQYpemEurvT0CxwlCf7YNJdTjAgdjk5360fh5UaJzKxm7L+/CPm7MXGZqnCN/7yLxAIxxEg7VLCcve0b0K34NR85pEOnN5XPZIPA+RDGA2AqSVkTIuXB9kvYwkLYyHBx4+4d3si3DWpSrm25WDZ4ReUFS0FYUV/WCTgF86E6JOmXLubwGItgkLqpaqBhYbQR7eZv0e+kpMqdMwoUXVjKQFADlAjcDAbW/uUbW2o/pS7O27+vQnxHDftJojiPG0D/5MhDs3whNDnw46XNSo2dLmSRP7rfKlYxei5ypV6ax4zZ2FxfB5/41420R8rf/qVsBcHOe3uRXPj98610fVpzkcR74s9rHWD3pkL8dYH8xesyT9kYp00sDnBV+Q3dhnXU8hGFh+my0a8EdtTXZXDw1oU0Py1G5ogXtU16Sn5QnAc9n4CbwCfK77zy5gZobVNHwqLZcOhgvQ5LbI/wUorX/GLDBJ3UfmB13DteQAqjMKlRCU676/4q0iUTVq/eQjuKTuDGPv4OD/+DSd7yP1+xo6GIZYnfPT6xWZZfR8=
        client_secret: AgC3gzI6P66kqM3k7Xm/DgvRoKdPfyQ6Lt+KV+5KKWyh+s+4cxTXcK1Dc9ug8k2/OTgFPszObH1mzPLFfO1oFEJ4A6In3KkSHQtv00mh78gTL5RDrxbULLPR1a0egZSEJYkbsw/laot2E1Ua6zyiZErZLe3K2DKOr4dJG4IhmNOaKt233K6+oPNtZOwvlTU93/eN/RBicMWnELuJ0vnDHhKtKpLTzfTO5pbjE46ijCkyKMHVz059B6uzo2PB+81ugT5b3iiV4SJuGC21s4yme4PNdxA4tkREADkNCAibiScci4dbYOm9muLtBGB8WEyfBGpDIrKXqQGyukScGB1e6AXZ01zUbmuufO6qI3erJpaNoy6kR6fR/Xk2JoxTCcylHpiYuU6EPXzZA4qAhphQ3/5QClxFwXqjg785jI7VBerRsHTnkcq11A1LV7VSVgrMOzm04gAKhUbicpGc3uCYe7Rv1cTk4rXIC9LxsQmL+5CsoaVxZz6uzdeOUFszEwbicCP4K+KI5rgYdt2EkyOC674e9qrPoZrqxuuh0h9zgom8r91nwOF6gH0+swG3rASMCPDO04Z+05m2MSqrRzBLsel5kJa+saMf1Fz6Vb/xZfcnHbndmvmnyzLxfIslcnuJUSbba62j98OlDvAgznnmNdbsTfJB37/1TK2qbUb5cT7l9H1VN/Oh7foSM5+vFAxGclRJgG8dhLHlY2pTXP0lPJWg85UlcmnmPJMgpquaG+81KQ==

  httproutes:
    - name: grafana
      hostnames:
        - grafana.int.kyledev.co
      parentRefs:
        - name: homelab
          namespace: envoy-gateway-system
      rules:
        - backendRefs:
            - group: ""
              kind: Service
              name: kube-prometheus-stack-grafana
              port: 80
    - name: prometheus
      hostnames:
        - prometheus.int.kyledev.co
      parentRefs:
        - name: homelab
          namespace: envoy-gateway-system
      rules:
        - backendRefs:
            - group: ""
              kind: Service
              name: kube-prometheus-stack-prometheus
              port: 9090
