apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: envoy-gateway-system:main
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: envoy-gateway-system
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://github.com/kdwils/homelab"
    path: infra/envoy-gateway/homelab
    targetRevision: homelab
  project: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
