apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-static
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: cert-manager
            namespace: cert-manager
            path: infra/cert-manager
          - name: nfs-provisioner
            namespace: nfs-provisioner
            path: infra/nfs-provisioner
          - name: system-upgrade
            namespace: system-upgrade
            path: infra/system-upgrade
  template:
    metadata:
      name: "{{name}}"
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      destination:
        namespace: "{{namespace}}"
        server: "https://kubernetes.default.svc"
      source:
        path: "{{path}}"
        repoURL: "https://github.com/kdwils/homelab"
        targetRevision: HEAD
      project: infra
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
