apiVersion: v2
name: crowdsec
description: CrowdSec security platform with homelab chart for HTTPRoute and SealedSecrets
version: 0.1.0
dependencies:
  - name: crowdsec
    version: 0.23.0
    repository: https://crowdsecurity.github.io/helm-charts
  - name: homelab-chart
    version: 0.1.27
    repository: oci://ghcr.io/kdwils/charts
    alias: homelab
