---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hoarder
  namespace: hoarder
spec:
  encryptedData:
    NEXTAUTH_PUBLIC_SECRET: AgDXkJtViCE7nETmp7rT/vdap44WlofUzHW3Hws/EEc1fDDJrMaJ/HCdloxd3pWjCW3TY0A5zhcNOAnAKL/WJso/lhmQ28qwDVeA+B5wXW2U5d+wfzw04vMaUQymhV0sd/pJtEHsx4RMBGOV6k2TWBMjPcW1u0ZA0CG8N/0OafE7Km4zdgTjZgK9ELSaaq6QrXXxjIxRPGjYeK3MgBQqCFZ5C4NoRiHcREajwvLBn83h6tgDkJ5qSEqPOrrp/o6CsmYpMSDgALM8Jp14wsNXlNQED4803ZuS6h8rzDArC9MJ1PjO10k5zbUNs1HOkLVnnvsshrsy5DSpIrb3IbNHZfHMAEz1XaQfmKyiAifb+Wp4QCpyq1yIbSbk7PsH4Ejal9HlzWMrsPU1DyMxT+A//bav3UBi9l+Y3EHJ+u1pLLrwb4Q8sFsHALGxclOSKMISnbFcc/4GOVvzSmLGAA6UaVkMq/dHkLfVOHegsJMb8Gqvqstl6NJanFRCRzaP48oTaF2WvWFJ04PHwGCsR2FwDMG9nNSdNCRr07zq4akO8pIx3Fb7Yf8Bc958Y19FzADFy4Cm6CsY2iW7DBxI9L8TuWdi4ZEjmC4Ai2AvGE/7tN99utfvB/fVQ2uAeaeKia31JuDYBMkBAlXM8GaNxnogCS2DCqcNh4Cp85zPWf7NYTUTPHh79SgmAcCBGfnr2y8l3EUqgDe+Hb3N7cz5PQJCx0XtYL0LxeEPn6DfLikS8e2RdRWmD7eK+ZIf4A8bThTzZT8o
    NEXTAUTH_SECRET: AgBOeNH5Os88P9J1xRXo9v6t7XSlEYCmK9ppNgFd4O1XzZPWAYceqSqu/BWT3I14xJ56GehBE1GR78dYPiIFoyiw7Ek0qbp15fCTfjtcB1yRBaH9XbEcVKXgCDug3ad0hWGe50fb3f/pPL0Shu0FQ4ziqRZVmcYDiuBm2hkb1nTtJxhwUhWnMLYsgIdN8gsY2S46KvmtC/Gg2JZgK7NlwvG82kScdlDh0nbgMcb0w6heRr+FH/Owu8mn6dIOZ//MTnwfaoiLpK01ZMQ6oUqtCxiv3T7EhAaWCUHQnWWD6t8gvq5bjOiTFaBWPj4Kelri4CYda+bY+uobTDbFyxLvAf3f0MmNIP47+uNKADi/dPbgFTAMikwRsxC4rsHrBspMA7V9ILGCeCmLsuZtOQHYGBf11qS6OXIfkOFrcJZNxb7X5XOcKypu+AjZPPXzjhvX8GI9d6miKqaKGPNiJp2aLgac4n0kRKhhW+dTWH3ApaAviLT2o0Phf9/swBnJ6QH9Sj9TErFgtV7Fo1ZgpGh/4P+aeaEclz4jsBnREMk4N+WMoeG+i1E57h3dwP+0CBTzfk9Eb3aY/8wo0etN85Hf2mj1p1PHQUUyDYQ+dnWTuOYOgbRcMT77d05aLu4bOupSRb1ecXWjYZ96ydwCTHhrdcQBFYe6LGyJylXHrMeSFaEskKGmtC3fBVnaiyCBjZ1RZAEDxZWRzLrLnC9lISeGH+89FX5ILUc6AIQ2iELwwxT9aHKpf+zW8tI+n352rrk0UDRq
    OAUTH_CLIENT_SECRET: AgC4/AVKlTpYqfjOGaJ3+3ugS3UUMYshxdSBaXL0AiChtxJkYcF09+8681Hf86nE8epUZFPCXl/WCwl/xMYTFJm8PnkimcMUHbfERmu8+X7LKStKpnrRf5rObad2gSW3B4FGhpTzRKxf+Npg+nwINWRFiKtJfig4y2l2wWttQt6/lYFbPeYECNbV8ncj3X7T0PbJwTy/4WXGvLYus4Fb47wYxMpunAgIAmoJ0URRlnN2Q7ho7cvonx9G03PI1UhXR0k2LotlbxERKQs/BSNrG8DDwpVzoytv1agXPsleIeOQg5zjCf+r4jHyjNjl/2v3zaGVYXtvzo8Wx9SPJ7IRqHiufXVpcGzn6ziiClYrVUGwUBODLvL72W1lq2xqf/bkBsUlpeEJQsOjZbMqdO2kCwjePHtDut4LuQxQNmdcfa9l2MOY4m/Z791esZ1HAXDBN5TIOBdYgQaV7EFNcgkgXs/BEXB8Qlv8oWMxZYRiDlHol6D0gJfH9ZB4d7a4r2G0Nu7HTazDNpQgXE+VlJV+WMazt3AaalI9+tO8pfVTo7fnh6DK+IhvLFI6mVlqWldIl96dQNhQ/LkZqlhupnAB7drFWWiSffDT4NXtzTjbw/HaN10ZwoK8eJaAl6FDDIme32zNWAVcQm7NoecaLAouWzYJXGI7dEhvDisxrAvawEyYPm2XerwJ5niswlDyrowIBaMdZ2Z1BrtN5Zq5yCCvDDwZI/yd/VaOt0vG+Knre0K8jw==
  template:
    metadata:
      name: hoarder
      namespace: hoarder
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: meilisearch
  namespace: hoarder
spec:
  encryptedData:
    MEILI_MASTER_KEY: AgC886RL+OWAHHsGLG82vV7MqdE3Bqq5avq6D858XQI0SToaCYTKPZ4K5oFW1b8crstOwRqBaFNTdrZUUxUKSuYpKTwuVtQky/e3KNBsUymNrGLgKpGYbqM3+dWSRZyVEP9AoN5YrhEF1yl0Sl0NY+sSBf6iqJt9f2tzjS/nZcB82ymxubsZ7zU0FwTyXeOsHMV733BUL/ibAzYU6uiPsyawgCIv1DWRh4yyaJ30KbTfANtvpNdWHHXwgyMkJbDuiJd+oS2lTO9jQ3VvwW9cEjXYjMPwg0yQBnKRQerkYbJN+NYr7lCCVhpAPfu8LqaCpfhyDLdslnQn4oyaISFxJqsfrqlfwzQoaJbdWYhMdT/PFwym0orzCTXzARVkVOgA0eqBLLJ+bPsPcMkQ31Y5pxZ3HvtwtRJ+wqItTzIDS9u1DUibcvv/timqrjy5Eo7Zcs2rFbQsUSOyf+mVliG+HurZaGdY5wny1H3PII/O0HKliY0OhwZS647KxQmXbdixQBWTRcjazN+DxwQ8G4N/PP6L7CSSYPXIdbITTMIijo3Rv/RdAAC4/tUxk6qomvvq2t8fT8nM2t5SVDJ9bH8EZgcwgo+fLB+8DvDdLcFZ4dJRDYx5p5aF5D2tNZlStLXFaL/6dcqVG0lYGllvCYAclQ8G3rsJvz7HHYatzLuiNOm39cJfssJw7jxL1NheoejgSNxaTecYvmlS92+7O44JXPJLS8WwpYX1EIYW84L66NuDVfBOReqiJE+HOZOUYPsq+5M=
  template:
    metadata:
      name: meilisearch
      namespace: hoarder
    type: Opaque
