apiVersion: v2
name: longhorn
description: longhorn
version: 0.1.0
dependencies:
  - name: longhorn
    version: 1.11.1
    repository: https://charts.longhorn.io
    alias: longhorn
  - name: homelab-chart
    version: 0.1.29
    repository: oci://ghcr.io/kdwils/charts
    alias: homelab
