---
# Source: homelab/charts/mgnx/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mgnx
  labels:
    helm.sh/chart: mgnx-0.1.22
    app.kubernetes.io/name: mgnx
    app.kubernetes.io/instance: mgnx
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: mgnx
      app.kubernetes.io/instance: mgnx
  template:
    metadata:
      labels:
        helm.sh/chart: mgnx-0.1.22
        app.kubernetes.io/name: mgnx
        app.kubernetes.io/instance: mgnx
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: default
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: mgnx
          image: "ghcr.io/kdwils/mgnx:sha-dabc0daf0b4598d8832f4428b690c405e3aac2b3"
          imagePullPolicy: IfNotPresent
          args:
            - serve
            - --config=/app/config.yaml
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: MGNX_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: uri
                  name: mgnx-app
