---
# Source: homelab/charts/mgnx/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mgnx-config
  labels:
    helm.sh/chart: mgnx-0.1.24
    app.kubernetes.io/name: mgnx
    app.kubernetes.io/instance: mgnx
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
data:
  config.yaml: |
    dht:
      port: 47444
      nodes_path: /data/nodes.dat
      bootstrap_nodes:
        - dht.libtorrent.org:25401
        - dht.transmissionbt.com:6881
        - router.bittorrent.com:6881
      workers: 4
      rate_limit: 25
      rate_burst: 25
      discovery_buffer: 10000
      good_node_window: 15m
      bad_failure_threshold: 2
      bucket_size: 8
      stale_threshold: 15m
      transaction_timeout: 10s
      token_rotation: 5m
      alpha: 3
      max_iterations: 4
  
    crawler:
      crawlers: 2
  
    server:
      port: 8080
      log_level: debug
  
    indexer:
      workers: 20
      request_timeout: 6s
      max_peers: 100
      rate_limit: 2
      rate_burst: 4
      min_size: 52428800     # 50 MB
      max_size: 161061273600 # 150 GB
  
    scrape:
      workers: 5
      rate_limit: 2
      rate_burst: 4
      batch_size: 74
      poll_interval: 30s
      dial_timeout: 5s
      read_timeout: 10s
      dead_after: 2160h  # 90 days
      prune_interval: 24h
      trackers:
        - udp://open.stealth.si:80/announce
        - udp://wepzone.net:6969/announce
        - udp://tracker.theoks.net:6969/announce
        - udp://tracker.srv00.com:6969/announce
        - udp://tracker.qu.ax:6969/announce
        - udp://tracker.dler.org:6969/announce
        - udp://tracker.darkness.services:6969/announce
        - udp://tracker.corpscorp.online:80/announce
        - udp://tracker.004430.xyz:1337/announce
        - udp://t.overflow.biz:6969/announce
        - udp://leet-tracker.moe:1337/announce
        - udp://d40969.acod.regrucolo.ru:6969/announce
        - udp://bittorrent-tracker.e-n-c-r-y-p-t.net:1337/announce
        - udp://6ahddutb1ucc3cp.ru:6969/announce
        - udp://udp.tracker.projectk.org:23333/announce
        - udp://tracker.tryhackx.org:6969/announce
        - udp://tracker.therarbg.to:6969/announce
        - udp://tracker.t-1.org:6969/announce
        - udp://tracker.plx.im:6969/announce
        - udp://tracker.playground.ru:6969/announce
        - udp://tracker.opentorrent.top:6969/announce
        - udp://tracker.ixuexi.click:6969/announce
        - udp://tracker.gmi.gd:6969/announce
        - udp://tracker.fnix.net:6969/announce
        - udp://tracker.flatuslifir.is:6969/announce
        - udp://tracker.ducks.party:1984/announce
        - udp://tracker.ddunlimited.net:6969/announce
        - udp://tracker.bluefrog.pw:2710/announce
        - udp://tracker.bittor.pw:1337/announce
        - udp://tracker.1h.is:1337/announce
        - udp://tr4ck3r.duckdns.org:6969/announce
        - udp://torrentclub.online:54123/announce
        - udp://seedpeer.net:6969/announce
        - udp://rekcart.duckdns.org:15480/announce
        - udp://open.dstud.io:6969/announce
        - udp://open.demonoid.ch:6969/announce
        - udp://ns575949.ip-51-222-82.net:6969/announce
        - udp://martin-gebhardt.eu:25/announce
        - udp://ipv4announce.sktorrent.eu:6969/announce
        - udp://evan.im:6969/announce
        - udp://bandito.byterunner.io:6969/announce
---
# Source: homelab/charts/mgnx/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mgnx-data
  labels:
    helm.sh/chart: mgnx-0.1.24
    app.kubernetes.io/name: mgnx
    app.kubernetes.io/instance: mgnx
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi
---
# Source: homelab/charts/mgnx/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mgnx
  labels:
    helm.sh/chart: mgnx-0.1.24
    app.kubernetes.io/name: mgnx
    app.kubernetes.io/instance: mgnx
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 47444
      targetPort: 47444
      protocol: UDP
      name: udp
  selector:
    app.kubernetes.io/name: mgnx
    app.kubernetes.io/instance: mgnx
---
# Source: homelab/charts/mgnx/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mgnx
  labels:
    helm.sh/chart: mgnx-0.1.24
    app.kubernetes.io/name: mgnx
    app.kubernetes.io/instance: mgnx
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: mgnx
      app.kubernetes.io/instance: mgnx
  template:
    metadata:
      labels:
        helm.sh/chart: mgnx-0.1.24
        app.kubernetes.io/name: mgnx
        app.kubernetes.io/instance: mgnx
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: default
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      initContainers:
        - name: gluetun
          restartPolicy: Always
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
            runAsNonRoot: false
            runAsUser: 0
          image: "ghcr.io/qdm12/gluetun:v3.41"
          imagePullPolicy: IfNotPresent
          ports:
            - name: 
              containerPort: 9999
              protocol: TCP
          env:
            - name: DNS_KEEP_NAMESERVER
              value: "on"
            - name: DOT
              value: "off"
            - name: FIREWALL_DEBUG
              value: "on"
            - name: FIREWALL_INPUT_PORTS
              value: "47444"
            - name: FIREWALL_OUTBOUND_SUBNETS
              value: "10.42.0.0/16,10.43.0.0/16"
            - name: FIREWALL_VPN_INPUT_PORTS
              value: "47444"
            - name: OPENVPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: OPENVPN_PASSWORD
                  name: openvpn
            - name: OPENVPN_PROTOCOL
              value: "tcp"
            - name: OPENVPN_USER
              valueFrom:
                secretKeyRef:
                  key: OPENVPN_USERNAME
                  name: openvpn
            - name: SERVER_CATEGORIES
              value: "p2p"
            - name: SERVER_COUNTRIES
              value: "United States"
            - name: VPN_SERVICE_PROVIDER
              value: "nordvpn"
            - name: VPN_TYPE
              value: "openvpn"
      containers:
        - name: mgnx
          image: "ghcr.io/kdwils/mgnx:sha-4d64df9d070b01e057c29e0f589ba8bf8d095e70"
          imagePullPolicy: IfNotPresent
          args:
            - serve
            - --config=/app/config.yaml
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: udp
              containerPort: 47444
              protocol: UDP
          volumeMounts:
            - mountPath: /data
              name: pvc-mgnx-data
              readOnly: false
            - mountPath: /app/config.yaml
              name: configmap-mgnx-config
              readOnly: true
              subPath: config.yaml
          env:
            - name: MGNX_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: uri
                  name: mgnx-app
      volumes:
        - name: pvc-mgnx-data
          persistentVolumeClaim:
            claimName: mgnx-data
        - configMap:
            name: mgnx-config
          name: configmap-mgnx-config
---
# Source: homelab/charts/mgnx/templates/postgres.yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: mgnx
  labels:
    helm.sh/chart: mgnx-0.1.24
    app.kubernetes.io/name: mgnx
    app.kubernetes.io/instance: mgnx
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  instances: 1
  storage:
    size: 50Gi
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
  bootstrap:
    initdb:
      database: mgnx
      owner: mgnx
---
# Source: homelab/charts/mgnx/templates/httproute.yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mgnx
  labels:
    helm.sh/chart: mgnx-0.1.24
    app.kubernetes.io/name: mgnx
    app.kubernetes.io/instance: mgnx
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: homelab
      namespace: envoy-gateway-system
  hostnames:
    - "torznab.int.kyledev.co"
    - "torznab.ts.kyledev.co"
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      backendRefs:
        - group: ""
          kind: Service
          name: mgnx
          port: 8080
          weight: 1
---
# Source: homelab/charts/mgnx/templates/udproute.yaml
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
  name: mgnx
  labels:
    helm.sh/chart: mgnx-0.1.24
    app.kubernetes.io/name: mgnx
    app.kubernetes.io/instance: mgnx
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  parentRefs:
    - name: homelab
      namespace: envoy-gateway-system
      sectionName: mgnx
  rules:
    - backendRefs:
      - name: mgnx
        port: 47444
