---
# Source: homelab/charts/mgnx/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mgnx-config
  labels:
    helm.sh/chart: mgnx-0.1.27
    app.kubernetes.io/name: mgnx
    app.kubernetes.io/instance: mgnx
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
data:
  config.yaml: |
    dht:
      port: 6881
      nodes_path: /data/nodes.dat
      forwarded_port_file: "/tmp/gluetun/forwarded_port"
      external_ip_file: "/tmp/gluetun/ip"
      workers: 10
      rate_limit: 300
      rate_burst: 150
      bad_failure_threshold: 3
      transaction_timeout: 3s
      max_nodes_per_response: 256
      max_peers_per_response: 50
      bucket_size: 20
      stale_threshold: 5m
  
    crawler:
      crawlers: 20
      discovery_workers: 50
      discovery_queue_size: 4096
      traversal_width: 50
      bootstrap_nodes:
        - dht.libtorrent.org:25401
        - dht.transmissionbt.com:6881
        - router.bittorrent.com:6881
        - router.utorrent.com:6881
      alpha: 3
      max_iterations: 8
      max_interval: 3m
      default_interval: 45s
      max_jitter: 30s
      bloom_rotation: 5m
      sample_enqueue_timeout: 50ms
      node_cache_cleanup: 1h
  
    server:
      log_level: info
      torznab_port: 8080
      health_port: 8081
      metrics_port: 9090
  
    indexer:
      workers: 20
      max_concurrent_peers: 30
      request_timeout: 2s
      max_peers: 30
      rate_limit: 200
      rate_burst: 400
      exclude_adult_content: true
      min_size: 10485760 # 10 MB
  
    scrape:
      batch_size: 74
      poll_interval: 10m
      dial_timeout: 3s
      read_timeout: 5s
      dead_after: 2160h # 90 days
      prune_interval: 24h
      trackers:
        - udp://tracker.opentrackr.org:1337/announce
        - udp://open.stealth.si:80/announce
        - udp://tracker.torrent.eu.org:451/announce
        - udp://tracker.theoks.net:6969/announce
        - udp://tracker.srv00.com:6969/announce
        - udp://tracker.qu.ax:6969/announce
        - udp://tracker.dler.org:6969/announce
        - udp://tracker.darkness.services:6969/announce
        - udp://tracker.004430.xyz:1337/announce
        - udp://tracker-udp.gbitt.info:80/announce
        - udp://t.overflow.biz:6969/announce
        - udp://opentracker.io:6969/announce
        - udp://explodie.org:6969/announce
        - udp://bittorrent-tracker.e-n-c-r-y-p-t.net:1337/announce
        - udp://utracker.ghostchu-services.top:6969/announce
        - udp://udp.tracker.projectk.org:23333/announce
        - udp://tracker.yume-hatsuyuki.moe:6969/announce
        - udp://tracker.tvunderground.org.ru:3218/announce
        - udp://tracker.tryhackx.org:6969/announce
        - udp://tracker.torrust-demo.com:6969/announce
        - udp://tracker.therarbg.to:6969/announce
        - udp://tracker.t-1.org:6969/announce
        - udp://tracker.plx.im:6969/announce
        - udp://tracker.playground.ru:6969/announce
        - udp://tracker.opentorrent.top:6969/announce
        - udp://tracker.ixuexi.click:6969/announce
        - udp://tracker.gmi.gd:6969/announce
        - udp://tracker.fnix.net:6969/announce
        - udp://tracker.flatuslifir.is:6969/announce
        - udp://tracker.filemail.com:6969/announce
        - udp://tracker.ducks.party:1984/announce
        - udp://tracker.ddunlimited.net:6969/announce
        - udp://tracker.corpscorp.online:80/announce
        - udp://tracker.bluefrog.pw:2710/announce
        - udp://tracker.bittor.pw:1337/announce
        - udp://tracker.1h.is:1337/announce
        - udp://tr4ck3r.duckdns.org:6969/announce
        - udp://torrentclub.online:54123/announce
        - udp://seedpeer.net:6969/announce
        - udp://rekcart.duckdns.org:15480/announce
        - udp://open.dstud.io:6969/announce
        - udp://open.demonoid.ch:6969/announce
        - udp://ns575949.ip-51-222-82.net:6969/announce
        - udp://martin-gebhardt.eu:25/announce
        - udp://leet-tracker.moe:1337/announce
        - udp://ipv4announce.sktorrent.eu:6969/announce
        - udp://evan.im:6969/announce
        - udp://bandito.byterunner.io:6969/announce
---
# Source: homelab/charts/mgnx/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mgnx-data
  labels:
    helm.sh/chart: mgnx-0.1.27
    app.kubernetes.io/name: mgnx
    app.kubernetes.io/instance: mgnx
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi
---
# Source: homelab/charts/mgnx/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mgnx
  labels:
    helm.sh/chart: mgnx-0.1.27
    app.kubernetes.io/name: mgnx
    app.kubernetes.io/instance: mgnx
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 6881
      targetPort: 6881
      protocol: UDP
      name: udp
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: mgnx
    app.kubernetes.io/instance: mgnx
---
# Source: homelab/charts/mgnx/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mgnx
  labels:
    helm.sh/chart: mgnx-0.1.27
    app.kubernetes.io/name: mgnx
    app.kubernetes.io/instance: mgnx
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: mgnx
      app.kubernetes.io/instance: mgnx
  template:
    metadata:
      labels:
        helm.sh/chart: mgnx-0.1.27
        app.kubernetes.io/name: mgnx
        app.kubernetes.io/instance: mgnx
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: default
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      initContainers:
        - name: gluetun
          restartPolicy: Always
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
            runAsNonRoot: false
            runAsUser: 0
          image: "ghcr.io/qdm12/gluetun:v3.41"
          imagePullPolicy: IfNotPresent
          ports:
            - name: health
              containerPort: 9999
              protocol: TCP
          volumeMounts:
            - mountPath: /tmp/gluetun
              name: gluetun-data
          env:
            - name: DNS_KEEP_NAMESERVER
              value: "on"
            - name: DOT
              value: "off"
            - name: FIREWALL_OUTBOUND_SUBNETS
              value: "10.42.0.0/16,10.43.0.0/16"
            - name: PORT_FORWARD_ONLY
              value: "on"
            - name: SERVER_COUNTRIES
              value: "United States"
            - name: VPN_PORT_FORWARDING
              value: "on"
            - name: VPN_SERVICE_PROVIDER
              value: "protonvpn"
            - name: VPN_TYPE
              value: "wireguard"
            - name: WIREGUARD_ADDRESSES
              value: "10.2.0.2/32"
            - name: WIREGUARD_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  key: WIREGUARD_PRIVATE_KEY
                  name: protonvpn
      containers:
        - name: mgnx
          image: "ghcr.io/kdwils/mgnx:sha-ad6dd3885582a284059ccf674b866215ffd6b673"
          imagePullPolicy: IfNotPresent
          args:
            - serve
            - --config=/app/config.yaml
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: udp
              containerPort: 6881
              protocol: UDP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /liveness
              port: 8081
            initialDelaySeconds: 300
            periodSeconds: 10
            timeoutSeconds: 2
          readinessProbe:
            failureThreshold: 54
            httpGet:
              path: /readiness
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
          volumeMounts:
            - mountPath: /data
              name: pvc-mgnx-data
              readOnly: false
            - mountPath: /app/config.yaml
              name: configmap-mgnx-config
              readOnly: true
              subPath: config.yaml
            - mountPath: /tmp/gluetun
              name: gluetun-data
              readOnly: true
          env:
            - name: MGNX_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: uri
                  name: mgnx-app
      volumes:
        - name: pvc-mgnx-data
          persistentVolumeClaim:
            claimName: mgnx-data
        - configMap:
            name: mgnx-config
          name: configmap-mgnx-config
        - emptyDir: {}
          name: gluetun-data
---
# Source: homelab/charts/mgnx/templates/postgres.yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: mgnx
  labels:
    helm.sh/chart: mgnx-0.1.27
    app.kubernetes.io/name: mgnx
    app.kubernetes.io/instance: mgnx
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  instances: 1
  storage:
    size: 50Gi
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
  bootstrap:
    initdb:
      database: mgnx
      owner: mgnx
---
# Source: homelab/charts/mgnx/templates/httproute.yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mgnx
  labels:
    helm.sh/chart: mgnx-0.1.27
    app.kubernetes.io/name: mgnx
    app.kubernetes.io/instance: mgnx
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: homelab
      namespace: envoy-gateway-system
  hostnames:
    - "mgnx.int.kyledev.co"
    - "mgnx.ts.kyledev.co"
  rules:
    - matches:
        - path:
            value: /metrics
      backendRefs:
        - group: ""
          kind: Service
          name: mgnx
          port: 9090
          weight: 1
    - matches:
      - path:
          type: PathPrefix
          value: /
      backendRefs:
        - group: ""
          kind: Service
          name: mgnx
          port: 8080
          weight: 1
---
# Source: homelab/charts/mgnx/templates/sealedsecret.yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: protonvpn
  namespace: media
spec:
  encryptedData:
    WIREGUARD_PRIVATE_KEY: AgBn5oO5B5M+dEFT5CoTuPF90CEcsTmVg6ISV9kg8+ZT4/TBHk5XxbTO4v3HKr8+NGDk0NZbrobtFSKljVYtYDJPrJ/nVTcjHd9omRxS3j6jgEiRytPA/YngUWA3HLFiWRpqDl0OvoBCtz49QqswJ6Wx2RkaRVgyE6JB+n5JZKcEVX4q0UBcpDHiDfAr0W0tq8vif/3vPfj7XkuEO9LIfLLnG2C1uJJfTvCvRHsjf2UmrNxPeqBwMf7pjPWzgZtfdGfk4FtYtJoi2CVLxW1ajOWrLfvQQqAWE7aOa8J4jV2jc89LAFnq4T0LbgSXydBgtV8QihI1xJsh5Tmbj14OtZT+094z40w8wItzDAZT6Dhxd8s6chbh34mbg5vdrxVKoXV7vV7JYxXkMJh1PO4ygnEubU/tx1knfw2A5OsS//nwGr5sCZhIqBqhy7KpLgQPquKnyJ3Tg/V8QNX8I7RhMXZw0zotuwT+JarvtppJZZZwX21HBUT+u4olTsOn63Y/qF4z3c37lH1923ACzUPK/i32y3aB16CV7y/MVS5imDnMpkSg4kjvx2/MmUxXfAfJn6I+JJyhmcG3+9PSDFNNUswv9HJ/lj0hYO5DcUu2VVGwOhASzGEhas2rb+8tNvSeuYLnmRjVv9MfJQkk7V4QCYbbdejy42f4eNXY1yGDFeDw3wC2p537bYZ9dObRsHrjBXF/bH98dCDxKVW/Y9cn8KblBZYbJ4AFgrNO+vqW/i8KHfNxUvwRtSgemIM+WQ==
  template:
    type: Opaque
    metadata:
      name: protonvpn
      namespace: media
---
# Source: homelab/charts/mgnx/templates/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mgnx
  labels:
    helm.sh/chart: mgnx-0.1.27
    app.kubernetes.io/name: mgnx
    app.kubernetes.io/instance: mgnx
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mgnx
      app.kubernetes.io/instance: mgnx
  endpoints:
    - port: "metrics"
      path: "/metrics"
      interval: "30s"
      scrapeTimeout: "10s"
